// 01-introduction.typ — Introduction: motivation and scope

= Introduction <introduction>

The global aviation industry consumes more than 100 billion gallons of jet fuel annually, making it one of the largest single-commodity supply chains in the world @Edwards2017. Every gallon must satisfy stringent thermophysical specifications before it is cleared for use in turbine engines, because the consequences of off-specification fuel range from degraded engine performance to catastrophic failure. The governing standards, ASTM D1655 for conventional petroleum-derived jet fuel and ASTM D7566 for fuels containing synthesized hydrocarbons (including sustainable aviation fuels, or SAFs), impose limits on dozens of properties @ASTMD1655 @ASTMD7566. Among these, three properties exert an outsized influence on combustion system design and flight safety. Viscosity governs fuel pumpability at low temperatures and atomization quality at the injector tip; surface tension controls droplet size distribution and subsequent evaporation during combustion; and density determines volumetric energy content, which directly sets aircraft range @Colket2017. Because turbine engines must operate across an enormous temperature window, from below $-40 degree.c$ during high-altitude cruise to above $100 degree.c$ in fuel-return lines near the engine, viscosity alone can vary by six orders of magnitude over the service envelope @Edwards2017.

The temperature dependence of liquid viscosity is well described by an Arrhenius-type relationship,

$ ln eta = A + B / T $ <arrhenius>

where $eta$ is the dynamic viscosity, $T$ is absolute temperature, and $A$ and $B$ are substance-specific constants @ASTMD341. This exponential sensitivity means that small compositional changes in a fuel blend can shift the viscosity--temperature curve enough to violate the $-20 degree.c$ or $-40 degree.c$ freezing-point limits mandated by D1655, making accurate property prediction across the full temperature range essential for fuel qualification.

The urgency of rapid property prediction is amplified by the global push toward sustainable aviation fuels. Decarbonizing aviation, which accounts for roughly 2--3\% of global $"CO"_2$ emissions, requires replacing petroleum-derived kerosene with fuels synthesized from biomass, waste oils, alcohols, or captured carbon dioxide @Holladay2020. Hundreds of candidate SAF pathways have been proposed, yet only about ten have received ASTM approval through the D4054 evaluation process @ASTMD4054. The bottleneck is qualification testing: a single new fuel pathway typically requires 3--5 years of evaluation and tens of millions of dollars in analytical and engine testing before it can be blended into the commercial fuel supply @Colket2017. At that pace, the portfolio of approved SAFs will not grow fast enough to meet the aviation industry's net-zero-by-2050 targets.

Traditional measurement of thermophysical properties compounds this bottleneck. Viscosity determination by capillary viscometry (ASTM D445) requires several milliliters of purified sample, temperature-controlled baths, and 30--60 minutes per data point; surface tension measurement by pendant-drop or Du Nouy ring tensiometry is similarly slow and sample-intensive @ASTMD445. For a candidate fuel with unknown composition, a full property screening across the relevant temperature range can consume days of laboratory time and hundreds of milliliters of material that may have been produced only at bench scale. These constraints create a strong incentive for predictive methods that can estimate fuel properties from minimal experimental input.

Nuclear magnetic resonance (NMR) spectroscopy offers a compelling alternative to exhaustive wet-chemistry characterization. A single proton ($""^1"H"$) or carbon-13 ($""^(13)"C"$) NMR spectrum, acquired in minutes on microliters of sample, encodes a complete molecular fingerprint: the types and connectivity of hydrogen and carbon atoms, the relative abundance of functional groups, and, for mixtures, the molar fractions of distinct chemical families @Cookson1987 @Edwards2017. Unlike chromatographic methods, NMR is non-destructive, requires no calibration standards, and provides quantitative composition data without prior knowledge of the analytes present. These attributes make NMR an attractive front-end measurement for a machine-learning pipeline that maps spectral features directly to thermophysical properties.

This report describes the development and evaluation of such a pipeline. Given an NMR spectrum of a pure compound or a fuel mixture, together with a target temperature, the goal is to predict viscosity, surface tension, and density with accuracy sufficient to support early-stage SAF screening. The approach is organized into four phases of increasing complexity: Phase~1 establishes baseline models using molecular fingerprints alone; Phase~2 introduces NMR spectral features and evaluates their predictive power for pure compounds; Phase~3 extends prediction to real fuel mixtures using composition-weighted spectral descriptors; and Phase~4 explores transfer learning from a large corpus of pure-compound NMR data to improve fuel-mixture predictions. By compressing the property-estimation step from days of laboratory work to minutes of spectral acquisition and computation, this framework aims to accelerate the screening and qualification of next-generation aviation fuels.
