// 01-introduction.typ — Introduction: motivation, NMR background, and scope

= Introduction <introduction>

The prediction of thermophysical properties from molecular structure is a central problem in chemical engineering, combustion science, and fuel qualification. For decades, empirical correlations and group contribution methods have served as the primary tools for estimating properties such as viscosity, surface tension, and density from knowledge of a compound's functional groups @Joback1987 @Constantinou1994 @Poling2001. These approaches work well for simple molecules within their training domain, but they struggle with the structural diversity and compositional complexity of real-world fuel mixtures. Machine learning offers a path beyond these limitations, provided that the molecular representation fed to the model captures enough structural information to support accurate generalization. This report investigates nuclear magnetic resonance spectroscopy as precisely such a representation. An NMR spectrum records, in a single rapid measurement, the complete distribution of hydrogen and carbon environments within a molecule or mixture, encoding the functional group inventory, connectivity patterns, and relative abundances that govern bulk thermophysical behavior. The central hypothesis is that NMR spectral features, when combined with modern regression methods, can predict temperature-dependent viscosity and surface tension with accuracy sufficient to accelerate the screening and qualification of aviation fuels.

The remainder of this introduction is organized as follows. @nmr-fundamentals provides a self-contained overview of NMR spectroscopy for readers who may not have a chemistry or spectroscopy background, establishing the physical principles and spectral features that underpin the molecular descriptors used throughout this work. @thermo-fuel-qualification motivates the practical application by describing the thermophysical properties critical to aviation fuel performance and the regulatory bottleneck that sustainable aviation fuel (SAF) candidates face during qualification. @scope-contributions summarizes the four-phase modeling pipeline developed in this report and highlights the principal contributions.


== Nuclear Magnetic Resonance Spectroscopy <nmr-fundamentals>

Nuclear magnetic resonance spectroscopy exploits a quantum-mechanical property of atomic nuclei known as spin. Certain isotopes, including hydrogen-1 ($""^1"H"$) and carbon-13 ($""^(13)"C"$), possess a nonzero spin angular momentum that causes them to behave as small magnetic dipoles. When an external magnetic field $B_0$ is applied, these nuclear dipoles align either with or against the field, occupying discrete energy levels separated by a gap $Delta E = gamma ℏ B_0$, where $gamma$ is the gyromagnetic ratio specific to each isotope and $ℏ$ is the reduced Planck constant. Irradiating the sample with radiofrequency energy that matches this energy gap induces transitions between spin states, a condition called resonance. The frequencies at which different nuclei resonate encode detailed information about their electronic environment and, by extension, the molecular structure surrounding them @Claridge2016 @Silverstein2014. Modern NMR spectrometers detect the free induction decay after a broadband excitation pulse and recover the frequency-domain spectrum by Fourier transformation. The entire measurement typically requires fewer than five minutes and consumes only microliters of sample, making NMR one of the most efficient analytical techniques available for organic structure determination.

Proton ($""^1"H"$) NMR is the most widely practiced variant of the experiment for two complementary reasons. First, the hydrogen-1 nucleus has the largest gyromagnetic ratio of any stable isotope other than tritium, giving it the highest intrinsic sensitivity per nucleus. Second, hydrogen is the most abundant element in organic molecules and is present in nearly every functional group of interest, so a single $""^1"H"$ spectrum surveys the entire carbon skeleton indirectly through its attached and nearby protons @Pavia2015 @Balci2005. These advantages make $""^1"H"$ NMR the default analytical tool for structure elucidation in organic chemistry, pharmaceutical development, and petrochemical analysis. Carbon-13 NMR provides complementary information by directly observing the carbon framework, but its natural abundance is only 1.1%, resulting in sensitivity roughly 5,700 times lower than that of $""^1"H"$. In practice, $""^(13)"C"$ spectra require longer acquisition times or isotopic enrichment and are therefore used as a supplement to, rather than a replacement for, proton NMR @Claridge2016.

The horizontal axis of a $""^1"H"$ NMR spectrum is reported in parts per million (ppm) of chemical shift $delta$ rather than in absolute frequency units. Chemical shift arises because the electrons surrounding each proton generate small local magnetic fields that partially shield the nucleus from the full external field $B_0$. Protons in electron-rich environments experience greater shielding and resonate at lower frequencies (smaller $delta$), while those near electronegative atoms or aromatic ring currents experience reduced shielding and resonate at higher frequencies (larger $delta$). All chemical shifts are measured relative to tetramethylsilane (TMS), which is assigned $delta = 0$ ppm by convention. Expressing the spectrum in ppm rather than hertz makes the peak positions independent of the spectrometer's operating frequency, so that spectra acquired on instruments of different field strengths can be compared directly @Silverstein2014. In practice, the $""^1"H"$ chemical shift range spans roughly 0 to 12 ppm. Aliphatic methyl and methylene groups appear between 0.5 and 2.0 ppm, protons adjacent to oxygen or nitrogen functionalities fall near 2.0 to 4.5 ppm, olefinic protons resonate between 4.5 and 6.5 ppm, aromatic ring protons occupy the 6.5 to 8.5 ppm region, and aldehyde or carboxylic acid protons appear furthest downfield near 9 to 12 ppm @Pavia2015. Because each class of chemical environment maps onto a characteristic ppm window, even a cursory visual inspection of the spectrum reveals which functional groups are present and in what relative proportions.

Beyond the position of each signal, the fine structure of NMR peaks carries additional structural information through a phenomenon known as scalar coupling (also called J-coupling or spin-spin splitting). When a proton has $n$ nonequivalent neighboring protons separated by two or three chemical bonds, its NMR signal splits into $n + 1$ lines. A proton with no coupled neighbors appears as a singlet, one neighboring proton produces a doublet, two neighbors produce a triplet, and so on. The spacing between the lines of a multiplet, measured in hertz and called the coupling constant $J$, is independent of the external magnetic field strength and depends instead on the dihedral angle, bond order, and hybridization connecting the coupled nuclei. Typical vicinal ($""^3 J_(H H)$) coupling constants range from about 2 Hz in strained rings to 16 Hz across trans-disubstituted double bonds @Claridge2016. Because coupling constants encode geometric relationships between bonded atoms, they provide information about molecular conformation that chemical shift alone cannot supply. Two-dimensional NMR experiments such as COSY (correlation spectroscopy), which maps $""^1"H"$--$""^1"H"$ coupling networks, and HSQC (heteronuclear single quantum coherence), which correlates each proton with its directly bonded $""^(13)"C"$, extend this connectivity analysis further, although the one-dimensional $""^1"H"$ spectrum remains the primary data source for the machine-learning models developed in this work @Lambert2019.

A third dimension of the $""^1"H"$ spectrum is integration. The area under each signal is directly proportional to the number of chemically equivalent protons giving rise to that signal, a property that is unique to NMR among common spectroscopic methods. A peak integrating as 3 relative to a peak integrating as 1, for example, indicates a methyl group versus a lone proton. Taken together, chemical shift, multiplicity, coupling constants, and integration allow a trained analyst to reconstruct the full connectivity of an unknown organic molecule from its $""^1"H"$ NMR spectrum alone, often without recourse to any other analytical technique @Silverstein2014.

These same attributes that make $""^1"H"$ NMR indispensable for human analysts also make it well suited as input to machine-learning models. A spectrum can be represented as a discrete list of peaks, each described by a chemical shift value, a relative intensity, and a multiplicity label, yielding a compact, standardized numerical descriptor that varies smoothly with molecular structure. Unlike molecular graph representations that require specialized graph neural network architectures @Gilmer2017Neural @Yang2019, an NMR peak list or binned spectrum can be consumed directly by conventional regression, ensemble, and feed-forward neural network methods. NMR spectra are also among the most reproducible analytical measurements in chemistry. Standardized reference databases, including the Human Metabolome Database (HMDB) @Wishart2022HMDB, NMRShiftDB2 @Kuhn2012nmrshiftdb2, and NMRexp @Wang2025NMRexp, store hundreds of thousands of quality-controlled spectra in uniform formats, providing a ready-made corpus for data-driven modeling. The Spectral Database for Organic Compounds (SDBS), maintained by the National Institute of Advanced Industrial Science and Technology in Japan, contributes an additional 35,000 $""^1"H"$ spectra with verified assignments @Saito2011SDBS @SDBS2025. The rich structural encoding inherent in $""^1"H"$ NMR, combined with its experimental standardization and broad chemical coverage, motivates its use as the primary molecular descriptor throughout this work.

For fuel mixtures specifically, NMR offers an advantage that no single-compound technique can match. A $""^1"H"$ spectrum of a multi-component fuel is the mole-fraction-weighted superposition of the spectra of its individual constituents @Cookson1987 @FlowerSaxena2005. The integrated areas of characteristic spectral regions, such as the aromatic (6.5--8.5 ppm), olefinic (4.5--6.5 ppm), and various aliphatic windows, directly quantify the functional group inventory of the entire mixture without requiring prior separation or identification of individual species. Abdul Jameel and coworkers demonstrated that these NMR-derived functional group fractions, termed atom types, can predict ignition quality, octane number, and other combustion-relevant properties of complex fuel blends with accuracy comparable to detailed compositional analysis @AbdulJameel2016Ignition @AbdulJameel2018Octane @AbdulJameel2018MFG. Parker et al. extended this framework to density and surface tension predictions for aviation fuels using NMR atom type descriptors @Parker2025DensityST. These precedents establish NMR as a proven front-end measurement for fuel property estimation and provide the methodological foundation on which the present work builds.


== Thermophysical Properties and Aviation Fuel Qualification <thermo-fuel-qualification>

The global aviation industry consumes more than 100 billion gallons of jet fuel annually, making it one of the largest single-commodity supply chains in the world @Edwards2017. Every gallon must satisfy stringent thermophysical specifications before it is cleared for use in turbine engines, because the consequences of off-specification fuel range from degraded engine performance to catastrophic in-flight failure. The governing standards, ASTM D1655 for conventional petroleum-derived jet fuel and ASTM D7566 for fuels containing synthesized hydrocarbons, impose limits on dozens of measurable properties @ASTMD1655 @ASTMD7566. Among these, three properties exert an outsized influence on combustion system design and flight safety, and understanding them in some detail is essential to appreciating why accurate prediction matters.

Viscosity, the resistance of a fluid to shear flow, governs two aspects of fuel system performance that are critical under extreme conditions. At the low temperatures encountered during high-altitude cruise (below $-40 °C$ for many flight profiles), excessive viscosity impedes fuel flow through pumps, filters, and transfer lines, potentially starving the engine of fuel. At the high temperatures found in fuel-return lines near the combustor (above $100 °C$), viscosity determines the quality of fuel atomization at the injector tip: a fuel that is too thin produces a spray of excessively fine droplets that evaporate prematurely, while one that is too thick yields large droplets that penetrate too far into the combustion chamber and burn incompletely @Colket2017. ASTM D1655 sets an upper viscosity limit of 8.0 $"mm"^2 slash "s"$ at $-20 °C$ for Jet A fuel and $-40 °C$ for Jet A-1, ensuring adequate pumpability at the coldest anticipated service temperatures @ASTMD1655. The temperature dependence of liquid viscosity is well described by an Arrhenius-type relationship,

$ ln eta = A + B / T $ <eq-arrhenius>

where $eta$ is the dynamic viscosity, $T$ is absolute temperature, and $A$ and $B$ are substance-specific constants @ASTMD341. This exponential sensitivity means that small compositional changes in a fuel blend can shift the viscosity-temperature curve by enough to violate specification limits, making accurate prediction across the full temperature range essential for fuel qualification.

Surface tension, the energy per unit area at the liquid-air interface, controls the initial breakup of the fuel jet emerging from the injector nozzle and the subsequent formation, coalescence, and evaporation of droplets within the combustion zone. Lower surface tension promotes finer atomization and faster evaporation, generally improving combustion efficiency and reducing soot formation. Higher surface tension produces larger droplets that require more time and distance to vaporize, shifting the heat-release profile downstream and increasing the risk of hot spots and incomplete combustion @Parker2025DensityST. Although surface tension varies less dramatically with temperature than viscosity does (typically decreasing linearly at a rate of roughly 0.1 $"mN" slash "m"$ per degree Celsius for hydrocarbons), its influence on spray dynamics makes it a key parameter in combustor design models. Density, the third property of primary interest, determines the volumetric energy content of the fuel and therefore the range achievable for a given tank volume. Fuel density also affects the momentum of the fuel jet and the pressure drop through metering orifices, both of which influence injector performance @Edwards2017.

Traditional measurement of these properties is slow and sample-intensive, compounding the bottleneck in fuel qualification. Viscosity determination by capillary viscometry following ASTM D445 requires several milliliters of purified sample, temperature-controlled baths equilibrated to within $plus.minus 0.01 °C$, and 30 to 60 minutes per data point @ASTMD445. Surface tension measurement by the pendant-drop or Du Nouy ring method is similarly time-consuming. For a candidate fuel of unknown composition, a full property screening across the relevant temperature range, from $-40 °C$ to $100 °C$, can consume days of laboratory time and hundreds of milliliters of material that may have been produced only at bench scale. These constraints create a powerful incentive for predictive methods that can estimate fuel properties from minimal experimental input.

The urgency of rapid property prediction is amplified by the global push toward sustainable aviation fuels. Aviation accounts for roughly 2 to 3 percent of global carbon dioxide emissions, and decarbonizing the sector requires replacing petroleum-derived kerosene with fuels synthesized from biomass, waste oils, alcohols, or captured carbon dioxide @Holladay2020. Hundreds of candidate SAF pathways have been proposed, spanning Fischer-Tropsch synthesis, hydroprocessed esters and fatty acids, alcohol-to-jet conversion, and catalytic hydrothermolysis, among others. Yet only about ten of these pathways have received ASTM approval through the D4054 evaluation process @ASTMD4054. The qualification of a single new fuel pathway typically requires three to five years of tiered evaluation, beginning with preliminary screening (Tier 1), proceeding through fit-for-purpose testing and rig-level combustion trials (Tiers 2 and 3), and culminating in full-scale engine tests (Tier 4), at a total cost that can reach tens of millions of dollars per pathway @Colket2017. At that pace, the portfolio of approved SAFs will not grow fast enough to meet the aviation industry's net-zero-by-2050 commitments.

A predictive framework that can estimate key thermophysical properties from a rapid analytical measurement would compress the earliest stages of this pipeline. Rather than synthesizing and physically testing every candidate blend, researchers could acquire a single NMR spectrum of the fuel or feedstock, extract spectral descriptors, and use trained machine-learning models to predict viscosity, surface tension, and density across the full operating temperature range. Candidates whose predicted properties fall outside specification limits could be eliminated immediately, reserving expensive physical testing for the most promising formulations. The NMR measurement itself is non-destructive, requires no calibration standards, and provides quantitative composition data without prior knowledge of the analytes present, making it an ideal front-end for such a screening pipeline @Cookson1987 @FlowerSaxena2005. This vision, from NMR spectrum to predicted fuel properties in minutes rather than months, motivates the modeling effort described in the remainder of this report.


== Scope and Contributions <scope-contributions>

This report describes the development, training, and evaluation of a four-phase machine-learning pipeline that predicts temperature-dependent viscosity and surface tension from molecular and spectral descriptors. Each phase addresses a distinct modeling challenge, and the phases are designed to build on one another so that representations learned on large pure-compound datasets can be transferred to the data-scarce domain of real fuel mixtures.

Phase 1 establishes baseline models using molecular fingerprints and computed descriptors alone, without any NMR data. Morgan circular fingerprints (2048-bit) and 195 RDKit molecular descriptors are computed from SMILES strings for 856 organic compounds whose experimental viscosity and surface tension data are available in NIST ThermoML @Frenkel2006ThermoML @NISTThermoMLArchive and the ChEDL chemicals library @Bell2025chemicals. Several regression architectures are compared, including feed-forward neural networks, XGBoost @Chen2016, random forests @Breiman2001, and ridge regression, under a rigorous compound-level cross-validation protocol that prevents temperature-based data leakage. Lasso feature selection reduces the descriptor space from nearly 1,700 dimensions to roughly 30 informative features per fold, and ensemble averaging over five independently trained models stabilizes predictions. Phase 1 serves two purposes: it quantifies the predictive ceiling achievable from molecular structure descriptors that do not require experimental measurement, and it provides the baseline against which NMR-based models are judged.

Phase 2 introduces NMR spectral features as molecular descriptors. Experimental $""^1"H"$ NMR peak lists from NMRShiftDB2 @Kuhn2012nmrshiftdb2 and NMRexp @Wang2025NMRexp are matched to the thermophysical property database by canonical SMILES, yielding a joint dataset of compounds for which both NMR spectra and measured properties are available. Three spectral encoding strategies are evaluated: binned histograms of the chemical shift axis, summary statistics of peak positions and intensities, and learned representations from a 1D convolutional neural network operating directly on the raw spectral vector. These NMR-only models are compared against the fingerprint baselines from Phase 1, and combined NMR-plus-fingerprint models are tested to determine whether NMR provides information that is complementary to computed molecular descriptors. The Phase 2 analysis reveals which spectral features carry the most predictive power and whether experimental NMR data can outperform purely computational molecular representations.

Phase 3 extends the pure-compound models to aviation fuel mixtures. Fuel-specific data, including NMR atom type distributions and measured bulk properties, are drawn from the Air Force Research Laboratory reference fuel database @Edwards2017, Parker et al. @Parker2025DensityST, and Abdul Jameel et al. @AbdulJameel2018MFG. Mixture-level descriptors are constructed by composition-weighting the pure-compound NMR features according to detailed hydrocarbon analysis or, where available, directly from the mixture-level $""^1"H"$ spectrum. The models are validated against measured properties of JP-5, Jet A, and several alternative aviation fuels (Fischer-Tropsch, HEFA, and alcohol-to-jet blends), with prediction accuracy reported as mean absolute percentage error at each temperature point.

Phase 4 investigates whether pretraining on a large corpus of pure-compound NMR-property pairs improves prediction accuracy on the small fuel-mixture dataset. A multilayer perceptron is first trained to predict viscosity and surface tension for approximately 1.48 million pure-compound records, learning a general mapping from NMR descriptors to thermophysical behavior. The pretrained network's intermediate representations are then fine-tuned on the fuel mixture data from Phase 3. This transfer-learning strategy is motivated by the severe data scarcity in the fuel domain, where fewer than 30 fuels have comprehensive NMR and property characterization, and by the hypothesis that the relationship between NMR features and bulk properties is sufficiently transferable across chemical classes to benefit from large-scale pretraining.

The principal contributions of this work are as follows. First, it assembles the largest joint NMR-thermophysical-property dataset used for machine-learning property prediction to date, linking 3.37 million NMR spectra from NMRexp with over one million experimental property data points from NIST ThermoML. Second, it provides the first systematic comparison of NMR spectral features against molecular fingerprint and descriptor baselines for viscosity and surface tension prediction under identical evaluation conditions. Third, it demonstrates end-to-end fuel property prediction from mixture-level NMR spectra for a panel of conventional and alternative aviation fuels, achieving mean absolute percentage errors below 15 percent for surface tension and competitive accuracy for viscosity. Fourth, it introduces a transfer-learning framework that leverages large-scale pure-compound pretraining to improve predictions in the data-limited fuel domain. All code, data pipelines, and trained model weights are provided to support reproducibility and extension by other researchers.
