// 02b-related-ml-molecular — Machine Learning for Molecular Property Prediction

=== Molecular Fingerprints as Feature Representations <fingerprints>

The encoding of molecular structure as fixed-length binary or count vectors---collectively termed molecular fingerprints---provided the representational foundation on which modern machine learning for property prediction was built. The earliest widely adopted fingerprint scheme was the Molecular ACCess System (MACCS) keys, developed by MDL Information Systems in the 1980s. MACCS keys define 166 publicly available structural queries, each corresponding to a single bit that records the presence or absence of a specific substructural fragment such as an aromatic ring, a carbonyl group, or a nitrogen-containing heterocycle @CeretoMassague2015. Because each bit position has a fixed chemical interpretation, MACCS keys are deterministic and readily interpretable, though they are limited by the finite vocabulary of fragments chosen by domain experts.

Complementary representations emerged in parallel. Carhart et al. introduced atom-pair descriptors, which enumerate every pair of atoms in a molecule along with the shortest topological path between them, capturing long-range connectivity patterns @Carhart1985. Nilakantan et al. proposed topological torsion descriptors, encoding sequences of four consecutively bonded non-hydrogen atoms together with their immediate chemical environments, thereby capturing short-range conformational information @Nilakantan1987. A transformative advance came with hashed path-based fingerprints, pioneered by Daylight Chemical Information Systems in the early 1990s. Rather than relying on a predefined fragment dictionary, the Daylight approach enumerates all linear bond paths up to a specified length, hashes each path to a bit position in a fixed-length vector, and folds the results together. This paradigm eliminated the need for expert curation of fragment libraries and allowed fingerprints to encode molecular features not anticipated by any predefined key set.

Building on foundations laid by Morgan's algorithm for canonical labeling of atoms at Chemical Abstracts Service @Morgan1965, Rogers and Hahn formalized Extended-Connectivity Fingerprints (ECFPs), a family of circular fingerprints that iteratively aggregate atomic neighborhoods outward to a specified radius @Rogers2010. ECFP4 (radius 2, diameter 4) and ECFP6 (radius 3) became the most widely adopted molecular representations in both academic and pharmaceutical research. Unlike path-based fingerprints, circular fingerprints capture branching substructures and represent an essentially unbounded vocabulary of molecular features through hashing. In the open-source RDKit toolkit, Morgan fingerprints are generated with configurable radius (commonly 2) and bit vector length (commonly 2048 bits), and this implementation has become the de facto standard for reproducible cheminformatics research @Landrum2006RDKit.

=== Fingerprints versus Molecular Descriptors <fp-vs-desc>

Although fingerprints were originally developed for similarity searching and virtual screening in chemical databases, their utility as feature vectors for quantitative structure--property relationship modeling became apparent as machine learning methods matured. Fingerprints offer advantages of computational speed, reproducibility, and robustness to conformational variability compared to three-dimensional descriptors @Muegge2016. Riniker and Landrum developed an open-source benchmarking platform to systematically compare fourteen different two-dimensional fingerprints across 88 biological targets, finding that circular fingerprints---particularly Morgan and ECFP variants---consistently ranked among the top performers for ligand-based virtual screening tasks @Riniker2013.

The relative merits of fingerprints and computed molecular descriptors for property prediction remain actively debated. Molecular descriptors, as catalogued comprehensively by Todeschini and Consonni @Todeschini2009 and implemented in packages such as Dragon @MauriDragon2006 and PaDEL-Descriptor @Yap2011, encode continuous-valued physicochemical quantities including molecular weight, topological polar surface area, and calculated partition coefficients that fingerprints alone cannot express. Orosz et al. compared MACCS, atom-pair, and Morgan fingerprints against traditional one-dimensional, two-dimensional, and three-dimensional molecular descriptors across six ADME-Tox endpoints using XGBoost and neural network models @Orosz2022. Their findings indicated that two-dimensional molecular descriptors generally outperformed fingerprints alone, particularly with tree-based algorithms, though the margin was algorithm-dependent. In a broader review, Wigh, Goodman, and Lapkin surveyed molecular representations for machine learning and categorized fingerprints as feature-based representations that sacrifice some information content for computational efficiency and fixed dimensionality @Wigh2022. Wieder et al. further demonstrated that compact molecular fingerprints can rival more elaborate descriptor sets when paired with appropriate learning algorithms, particularly for datasets of moderate size @Wieder2020Compact. In practice, many high-performing QSPR models concatenate fingerprints with computed descriptors, leveraging the complementary information each provides. For thermophysical property prediction specifically, fingerprints encode the presence and arrangement of functional groups that govern intermolecular interactions---hydrogen bonding, dispersion, polarity---while descriptors such as molecular weight and topological indices provide continuous-valued physicochemical context.

=== Random Forests for QSPR <random-forests>

The Random Forest algorithm, introduced by Breiman in 2001 @Breiman2001, rapidly became one of the most widely adopted machine learning methods in QSPR modeling. Svetnik et al. were among the first to systematically evaluate Random Forests for compound classification and QSAR, demonstrating performance among the most accurate methods available at the time across six cheminformatics datasets @Svetnik2003. Their work established Random Forests as the de facto baseline for molecular property prediction throughout the 2000s and early 2010s. Random Forests proved particularly well-suited to cheminformatics because they handle high-dimensional molecular descriptor spaces gracefully, provide intrinsic feature importance rankings through out-of-bag permutation measures, resist overfitting through bagging, and require minimal hyperparameter tuning. The built-in variable importance mechanism also serves as a principled feature selection tool for QSPR, enabling researchers to identify which molecular descriptors or fingerprint bits contribute most to predictive accuracy.

=== Gradient Boosting: XGBoost and LightGBM <gradient-boosting>

The introduction of XGBoost by Chen and Guestrin @Chen2016 and LightGBM by Ke et al. @Ke2017 marked a substantial advance in gradient boosted decision tree performance and scalability. XGBoost introduced sparsity-aware split finding and cache-optimized computation, while LightGBM achieved further speedups through gradient-based one-side sampling and exclusive feature bundling. In molecular property prediction, Sheridan et al. provided a landmark comparison of XGBoost against Random Forests and single-task deep neural networks on proprietary QSAR datasets, finding that XGBoost with default hyperparameters consistently outperformed Random Forests and achieved accuracy nearly matching deep neural networks at dramatically faster training times @Sheridan2016. This established gradient boosting as occupying a practical optimum between the simplicity of Random Forests and the complexity of deep learning, particularly for medium-sized tabular molecular descriptor datasets.

For thermophysical property prediction specifically, Chew et al. developed QSPR models for temperature-dependent viscosities of over 4000 organic molecules, finding that LightGBM with physics-informed molecular dynamics descriptors delivered the strongest descriptor-based prediction performance @Chew2024. SHAP analysis of their models revealed that intermolecular interaction features derived from molecular dynamics simulations ranked as the most important predictors, illustrating how gradient boosted trees facilitate mechanistic interpretation through feature importance decomposition. Earlier work by Katritzky et al. had demonstrated the effectiveness of ensemble methods with CODESSA descriptors for viscosity prediction of pure organic liquids @Katritzky2000viscosity, and the transition from linear and neural network QSPR to tree-based ensembles represented a consistent improvement across thermophysical property domains @Katritzky2010.

=== MoleculeNet Benchmarks and the Deep Learning Comparison <moleculenet>

The MoleculeNet benchmark introduced by Wu et al. provided the first standardized comparison framework spanning quantum mechanical, physical chemistry, biophysics, and physiology tasks @Wu2018MoleculeNet. While learnable graph-based representations---particularly graph convolutional networks---generally offered the best performance on larger datasets, the benchmark revealed that kernel methods and ensemble tree models were more robust under data scarcity and exhibited less overfitting on small training sets. The Directed Message Passing Neural Network (D-MPNN) architecture introduced by Yang et al. through the Chemprop package advanced the state of the art further, outperforming both traditional fingerprint-based models and earlier graph neural network variants on most MoleculeNet tasks @Yang2019. The subsequent Chemprop v2 release by Heid et al. expanded this framework with multi-task learning and uncertainty quantification capabilities @Heid2024Chemprop. However, descriptor-based models using XGBoost remained competitive in many settings, particularly when combined with well-engineered molecular descriptors. Cai et al. directly compared descriptor-based XGBoost and Random Forest models against graph neural network architectures on eleven public datasets, finding that tree-based models required only seconds to train while achieving comparable accuracy and offering superior interpretability through feature importance analysis @Cai2020.

=== When Trees Beat Deep Learning on Tabular Data <trees-vs-dl>

A rigorous empirical investigation by Grinsztajn et al., presented at NeurIPS 2022, demonstrated that tree-based models remain state-of-the-art on medium-sized tabular datasets---approximately 10,000 samples---even without accounting for their substantial computational advantages @Grinsztajn2022. The study identified several properties of tabular data that favor tree-based methods: the presence of uninformative features that trees handle through implicit feature selection, irregular target functions with sharp decision boundaries that piecewise-constant tree predictions approximate well, and the lack of rotational invariance in the data that tree splits exploit naturally. These findings have direct implications for molecular property prediction with engineered descriptors. When molecular representations take the form of fixed-length descriptor vectors---whether fingerprints, RDKit descriptors, or spectral features---the prediction task is fundamentally a tabular regression problem where gradient boosted trees excel. The interpretability of these models through SHAP values and feature importance rankings provides a further practical advantage in QSPR, enabling researchers to identify which structural or spectral features drive predictions and thereby build physical intuition about structure--property relationships. For thermophysical property prediction pipelines that combine multiple descriptor types, XGBoost and LightGBM therefore represent a well-justified methodological choice that balances predictive accuracy, training efficiency, and scientific interpretability.
