// 02c-related-dl-molecular.typ — Deep Learning and Spectral Methods

// =============================================================================
// Neural Networks and Learned Molecular Representations
// =============================================================================

=== Neural Networks and Learned Molecular Representations <nn-learned-repr>

The application of neural networks to molecular property prediction dates to the early 1990s, when multilayer perceptrons were first coupled with hand-engineered molecular descriptors for quantitative structure--property relationship modeling. Zupan and Gasteiger's 1993 textbook provided an accessible introduction that catalyzed adoption across chemical subdisciplines @Zupan1993Neural. Around the same period, Baskin, Palyulin, and Zefirov proposed a neural architecture that bypassed explicit descriptor computation altogether, feeding graph-derived atom-level features directly into a network whose topology enforced invariance to atom renumbering @Baskin1997Neural. These early efforts demonstrated that even shallow networks could rival or surpass linear regression when the descriptor space was sufficiently rich, but they were fundamentally limited by two constraints: the quality and completeness of the hand-crafted descriptor sets, and the modest dataset sizes typical of experimental chemistry.

A conceptual breakthrough arrived when researchers began allowing the neural network itself to learn molecular representations end-to-end, rather than relying on fixed fingerprints such as Extended-Connectivity Fingerprints. Lusci, Pollastri, and Baldi pioneered this direction by applying recursive neural networks to undirected molecular graphs for aqueous solubility prediction, demonstrating that learned representations could outperform hand-crafted descriptors on standard benchmarks @Lusci2013Deep. Duvenaud et al. extended this idea more generally with their "neural fingerprint" model, which replaced each layer of the circular fingerprint algorithm with a differentiable neural network layer operating on the molecular graph @Duvenaud2015Convolutional. This work was significant not merely for its predictive accuracy but for demonstrating that circular fingerprints were a special case of a broader, learnable family of molecular representations. Concurrently, Ramsundar et al. introduced massively multitask networks for drug discovery, training a single deep network on more than 200 biological activity datasets simultaneously and showing that shared representations across tasks improved prediction on individual endpoints @Ramsundar2015Massively. This was an early and influential demonstration of multi-task learning for molecular properties.

Kearnes et al. formalized the notion of molecular graph convolutions, introducing learnable edge features alongside node features and benchmarking the resulting architecture across diverse molecular property prediction tasks @Kearnes2016Molecular. Their work highlighted that operating on the full molecular graph, rather than on a fixed-radius fingerprint, allowed the network to capture long-range intramolecular interactions more naturally. The conceptual landscape was then unified by Gilmer et al., who proposed the Message Passing Neural Network (MPNN) framework @Gilmer2017Neural. The MPNN framework abstracted earlier graph-based models---including Duvenaud's neural fingerprints and Kearnes's graph convolutions---into a common formalism consisting of a message function, an update function, and a readout function. Applied to the QM9 quantum chemistry benchmark, MPNNs achieved state-of-the-art results on 11 of 13 target properties. This framework became the de facto reference architecture for molecular graph neural networks, and its vocabulary---message passing, aggregation, readout---pervades the field to this day.

Sch\"utt et al. developed SchNet, which introduced continuous-filter convolutional layers that operate on atomic positions in three-dimensional space rather than on a discrete bond graph @Schutt2018SchNet. By modeling interatomic distances with radial basis functions and learning filters in continuous space, SchNet could capture spatial interactions at arbitrary resolution, making it particularly effective for predicting quantum-mechanical properties of molecules and materials. Around the same time, Wu et al. released MoleculeNet, a standardized benchmark suite for molecular machine learning encompassing quantum mechanics, physical chemistry, biophysics, and physiology datasets @Wu2018MoleculeNet. MoleculeNet was distributed as part of the DeepChem open-source framework, which provided reference implementations of featurization pipelines and model architectures, establishing a common evaluation infrastructure that has shaped the field's trajectory.

// =============================================================================
// Graph Neural Networks: Expressiveness, Attention, and Geometry
// =============================================================================

=== Graph Neural Networks for Molecular Graphs <gnn-molecular>

The year 2019 saw a rapid diversification of GNN architectures addressing distinct limitations of the original GCN and MPNN designs. Kipf and Welling's Graph Convolutional Network (GCN) had established a spectral-inspired convolutional operation on graph-structured data, where each node aggregates information from its immediate neighbors via a normalized adjacency matrix @Kipf2017Semi. Though originally designed for citation networks, the GCN framework was quickly adopted for molecular graphs, where atoms serve as nodes and bonds as edges with atomic properties encoded as node features.

Xu et al. introduced the Graph Isomorphism Network (GIN), motivated by a theoretical analysis showing that standard GNNs are at most as powerful as the Weisfeiler--Leman graph isomorphism test in distinguishing non-isomorphic graphs @Xu2019How. GIN achieves maximal discriminative power within this bound by using a sum aggregator with learnable injective functions, making it provably as expressive as the 1-WL test. This work established a critical theoretical benchmark for GNN expressiveness that continues to shape the field, and Morris et al. extended the analysis to higher-order $k$-WL hierarchies @Morris2019Weisfeiler. In the domain of molecular fingerprints, Xiong et al. proposed AttentiveFP, which applies a graph attention mechanism to learn molecular representations directly from 2D molecular graphs @Xiong2020Pushing. AttentiveFP uses atom-level and molecule-level attention layers that weight the contributions of neighboring atoms according to learned relevance scores, enabling interpretable identification of substructures important for a given property. The model achieved state-of-the-art results across multiple MoleculeNet tasks including solubility, lipophilicity, and toxicity endpoints.

Also in 2019, Yang et al. introduced the Directed Message Passing Neural Network (D-MPNN), implemented in the Chemprop software package @Yang2019. Unlike standard MPNNs that pass messages between atoms, D-MPNN associates messages with directed edges, which prevents so-called "totters"---redundant message paths of the form $v_1 arrow v_2 arrow v_1$---that dilute information flow. Benchmarked across 19 public and 16 proprietary datasets, D-MPNN consistently matched or exceeded competing architectures and random-forest baselines with molecular fingerprints, establishing Chemprop as one of the most widely adopted GNN tools in cheminformatics. Heid et al. subsequently released an updated Chemprop package extending D-MPNN with support for multi-molecule systems, reaction property prediction, uncertainty quantification, and transfer learning workflows @Heid2024Chemprop.

Gasteiger et al. introduced DimeNet (Directional Message Passing for Molecular Graphs), which incorporates 3D geometric information---specifically interatomic distances and bond angles---into the message passing framework @Gasteiger2020Directional. By embedding messages between atom pairs and transforming them based on angular information, DimeNet captures directional interactions that are invisible to purely topological 2D GNNs, achieving substantial improvements on molecular energy and force prediction tasks. DimeNet and its faster successor DimeNet++ demonstrated that encoding 3D structure is essential for quantum-chemical property prediction, though at the cost of requiring 3D conformer generation as a preprocessing step. Hu et al. extended the benchmarking effort with the Open Graph Benchmark, which includes molecular datasets derived from MoleculeNet but with more rigorous scaffold-based splits and a leaderboard infrastructure that has driven rapid progress @Hu2020Open.

Despite their success, GNNs face several well-characterized limitations. The over-smoothing problem causes node representations to converge to indistinguishable states as the number of message-passing layers increases, effectively limiting GNN depth and the size of molecular neighborhoods that can be captured. The related phenomenon of over-squashing compresses information from exponentially growing receptive fields into fixed-size vectors, losing long-range dependencies. Wieder et al. catalogued over 80 GNN variants applied to more than 20 molecular properties across 48 datasets, confirming the breadth of GNN adoption while highlighting these persistent challenges @Wieder2020Compact. For thermophysical property prediction specifically, the requirement for large, high-quality training data remains a bottleneck: viscosity and surface tension datasets are orders of magnitude smaller than the drug-discovery datasets on which most GNN architectures were developed. Additionally, temperature and pressure dependence---critical for thermophysical applications---requires either multi-task formulations or auxiliary input features, as standard molecular GNNs encode only molecular structure and not thermodynamic state variables.

// =============================================================================
// Transformers and Self-Supervised Pretraining
// =============================================================================

=== Transformers and Self-Supervised Pretraining <transformers-pretraining>

The success of the Transformer architecture in natural language processing prompted researchers to investigate whether molecular strings could be treated as a chemical "language." Schwaller et al. provided an early and influential demonstration with the Molecular Transformer, which cast chemical reaction prediction as a sequence-to-sequence translation problem over SMILES strings, achieving over 90% top-1 accuracy on standard benchmarks without requiring hand-crafted atom mappings @Schwaller2019MolecularTransformer. Honda et al. introduced the SMILES Transformer, which used unsupervised encoder--decoder pretraining on a large SMILES corpus to learn continuous molecular fingerprints @Honda2020SMILESTransformer. This work showed that pretrained representations outperformed rule-based fingerprints and graph methods specifically in low-data regimes, a finding directly relevant to property prediction tasks with limited labeled compounds.

The bidirectional masked language modeling paradigm pioneered by BERT was quickly adapted for chemistry. Fabian et al. proposed MolBERT, which combined masked SMILES token prediction with domain-relevant auxiliary tasks such as molecular descriptor regression, demonstrating that injecting chemical knowledge during pretraining improved downstream virtual screening and QSAR performance even with a relatively modest four-million-compound pretraining set @Fabian2020MolBERT. Chithrananda et al. released ChemBERTa, adapting the RoBERTa architecture to 77 million PubChem SMILES with purely self-supervised masked language modeling, showing that performance scaled predictably with pretraining corpus size @Chithrananda2020ChemBERTa. Ahmad et al. extended this line with ChemBERTa-2, systematically comparing masked language modeling against multi-task supervised pretraining and establishing that multi-task pretraining on computed descriptors yielded the most transferable representations @Ahmad2022ChemBERTa2. Beyond token-level masking, contrastive self-supervised methods emerged as a complementary strategy. Wang et al. introduced MolCLR, which operates on molecular graphs rather than SMILES strings, applying stochastic augmentations---atom masking, bond deletion, subgraph removal---and training a GNN encoder with a contrastive objective that pulls augmented views of the same molecule together while pushing different molecules apart @Wang2022MolCLR.

A parallel thread addressed a fundamental limitation of SMILES-based models: the SMILES string is a linearization of molecular topology and discards explicit 3D spatial information. Ying et al. introduced Graphormer, a Transformer architecture for graph-structured data that encodes structural information through centrality encoding, spatial encoding based on shortest-path distances, and edge feature encoding in the attention mechanism @Ying2021Graphormer. Graphormer won first place in the OGB-LSC quantum property prediction challenge and demonstrated that standard Transformer attention, when properly augmented with graph-structural biases, can outperform specialized message-passing GNNs. Rampasek et al. generalized this direction with the GPS (General, Powerful, Scalable) framework, which decouples local message-passing from global Transformer attention, achieving linear complexity in the number of nodes and edges while matching or exceeding Graphormer's performance across 16 benchmarks @Rampasek2022GPS. Moving further toward physical realism, Zhou et al. proposed Uni-Mol, a universal 3D molecular pretraining framework that directly takes atomic 3D coordinates as input using an SE(3)-equivariant Transformer backbone @Zhou2023UniMol. Pretrained on 209 million molecular conformations with masked atom prediction and 3D position denoising tasks, Uni-Mol outperformed prior state-of-the-art on 14 of 15 molecular property prediction benchmarks, confirming that 3D geometric information provides substantial gains over 1D or 2D representations alone.

=== Transfer Learning for Small Datasets <transfer-small-datasets>

A persistent challenge in molecular property prediction is label scarcity: experimental measurements are expensive, and many target properties have only hundreds or low thousands of data points. Hu et al. systematically addressed this by evaluating strategies for pretraining graph neural networks @Hu2020Strategies. They showed that naive node-level or graph-level pretraining could lead to negative transfer, but a combined strategy---pretraining at both levels using self-supervised objectives on large unlabeled molecular corpora, followed by fine-tuning on the target task---yielded up to 9.4% absolute improvement in ROC-AUC on molecular property benchmarks. This work established pretraining as a viable strategy for molecular GNNs and stimulated a wave of follow-up research on self-supervised molecular representation learning.

These developments have collectively pushed the field toward chemical foundation models: large pretrained architectures intended to serve as general-purpose molecular encoders @Fang2025FoundationModelsPerspective. The central value proposition is that self-supervised pretraining on millions of unlabeled structures learns transferable chemical representations that can be fine-tuned with far fewer labeled examples, directly addressing the data scarcity that characterizes most experimental property prediction tasks. For a problem such as the one considered in this report, where fewer than 1,000 compounds have matched NMR spectra and thermophysical measurements, the pretrain-then-fine-tune paradigm is especially compelling: the model can learn general molecular syntax, substructure patterns, and conformational preferences from vast unlabeled corpora, then adapt to the specific NMR-to-property mapping with the limited labeled data available.

However, significant limitations remain. SMILES-based models are sensitive to tokenization choices and SMILES canonicalization. Graph Transformers require careful positional encoding design to capture the structural information that message-passing GNNs handle naturally. 3D pretraining methods such as Uni-Mol depend on the quality of conformer generation, which introduces noise for flexible molecules. Recent analyses have noted that foundation models for chemistry still struggle with out-of-distribution generalization and that the benefits of scale plateau when downstream tasks involve property types---such as bulk thermophysical properties---that are poorly represented in pretraining objectives focused on quantum-level or pharmacological endpoints @Fang2025FoundationModelsPerspective. For thermophysical applications specifically, GNN and Transformer models have been applied to viscosity prediction by Chew et al. @Chew2024 and to surface tension of polymers by Tamnanloo et al. @Tamnanloo2025Surface, but both studies found that incorporating physics-based features or domain-specific descriptors substantially improved predictions beyond what end-to-end learned representations achieved alone. These considerations motivate hybrid approaches that combine experimentally grounded spectroscopic descriptors with learned representations rather than relying solely on pretrained models.
