// 03a-data-nmr-databases — NMR Spectral Databases

The foundation of any data-driven approach to NMR-based property prediction is a large, structurally diverse corpus of molecular NMR spectra paired with unambiguous chemical identifiers. This section surveys the fourteen NMR spectral databases evaluated for this work, ranging from million-scale text-mined collections to small, expertly curated reference libraries. @tab-nmr-databases provides a summary of all databases considered, including their scale, data format, and access method. The databases span a wide range of provenance: some contain exclusively experimental measurements, others provide computationally predicted spectra, and several offer both. They also differ dramatically in data representation, from raw free induction decays (FIDs) to processed peak lists to bucketed pseudo-spectra, and in accessibility, from fully open REST APIs to Cloudflare-protected web interfaces with no programmatic access whatsoever.

#figure(
  table(
    columns: (1.4fr, 0.9fr, 0.9fr, 1.2fr, 1.6fr),
    align: (left, right, right, left, left),
    stroke: 0.5pt,
    inset: 5pt,
    table.header(
      [*Database*], [*Compounds*], [*Spectra*], [*Format*], [*Access Method*],
    ),
    [NMRexp], [1,480,000], [3,373,000], [Parquet peak lists], [Zenodo download],
    [NMRShiftDB2], [45,000], [70,000], [SDF / NMReDATA], [SourceForge bulk export],
    [SDBS], [34,600], [30,100#super[a]], [HTML images + metadata], [Web scraping],
    [NP-MRD], [281,859], [5,400,000#super[b]], [nmrML / JCAMP-DX / FID], [Bulk FTP download],
    [HMDB], [217,920], [313,380#super[c]], [XML / FID / peak lists], [Bulk download#super[d]],
    [BMRB/GISSMO], [3,315], [90,000#super[e]], [STAR / peak tables], [REST API / FTP],
    [nmrXiv], [---#super[f]], [151 projects], [Raw FID (vendor)], [REST API],
    [NMRBank], [149,135], [225,809], [CSV peak lists], [GitHub download],
    [2DNMRGym], [22,348], [22,348], [HSQC peak tables], [GitHub / HuggingFace],
    [PROSPRE], [577], [4,207 shifts], [Web / downloadable], [Web server],
    [IR-NMR], [1,255#super[g]], [1,255], [Parquet (DFT shifts)], [Zenodo download],
    [logD-NMR], [1,276], [1,276], [CSV (200-bin vectors)], [GitHub download],
    [BML-NMR], [208], [3,328], [FID / processed], [Offline#super[h]],
    [PubChem], [116,000,000], [---], [SMILES / InChI], [FTP bulk download],
  ),
  caption: [Summary of NMR spectral databases surveyed in this work. #super[a]Combined $""^1$H and $""^(13)$C NMR entries. #super[b]Includes 5M+ predicted spectra. #super[c]Approximately 400 experimental, remainder predicted. #super[d]Cloudflare WAF requires workaround. #super[e]Peak annotations from GISSMO spin simulations across 18 field strengths. #super[f]Compound count not directly reported; data organized by project. #super[g]NMR subset of 177,461-compound IR dataset. #super[h]Server unreachable since September 2025.],
) <tab-nmr-databases>

=== NMRexp <sec-nmrexp>

NMRexp is the largest publicly available database of experimental NMR spectra for organic molecules, published by Wang et al. in _Scientific Data_ in December 2025 @Wang2025NMRexp. Developed at Peking University and the AI for Science Institute in Beijing, NMRexp contains 3,372,987 experimental NMR records spanning six nuclei: $""^1$H (1,667,135 spectra), $""^(13)$C (1,455,670), $""^(19)$F (197,186), $""^(31)$P (33,456), $""^(11)$B (17,143), and $""^(29)$Si (2,397). Among the $""^1$H spectra alone, 1,417,781 unique compounds are represented, with approximately 8% of compounds having two or more independent measurements. The dataset was constructed by text-mining nearly 200,000 supporting information PDF documents from scientific publications spanning 2010 to 2024. The extraction pipeline employs a YOLO-based layout detection model to identify molecular structure diagrams and text blocks, an optical chemical structure recognition module to convert molecular images to SMILES strings, and approximately 60 regular expressions to parse NMR peak data. Each entry undergoes validation against fundamental NMR principles, including proton count consistency, monotonic chemical shift ordering, and plausible coupling constant ranges.

The dataset is distributed as Parquet files on Zenodo under a CC-BY-4.0 license. The primary file (661 MB) contains columns for SMILES, NMR type, spectrometer frequency, solvent, normalized peak text, structured peak lists with chemical shifts and multiplicities, and source DOIs for traceability. A filtered subset (529 MB, 2,853,590 entries) restricts to molecules with at most one stereogenic carbon. Manual validation of 300 randomly sampled entries confirmed greater than 99% accuracy in metadata extraction and 98% correctness in molecular skeleton assignment. Internal consistency tests on replicate spectra yielded mean absolute errors of 0.026 ppm for $""^1$H and 0.206 ppm for $""^(13)$C, substantially lower than the 0.09 ppm and 0.51 ppm reported for NMRShiftDB2. Known limitations include optical structure recognition errors in approximately 2% of molecular skeletons and stereochemistry recognition accuracy of only 83% for molecules with a single stereocenter. NMRexp surpasses existing open-access NMR databases by one to two orders of magnitude in scale, making it comparable to commercial databases while remaining fully open.

=== NMRShiftDB2 <sec-nmrshiftdb2>

NMRShiftDB2 is the longest-running open-access database of experimentally measured NMR chemical shifts, tracing its origins to the NMRShiftDB project initiated by Steinbeck and Kuhn at the Max-Planck-Institut in Jena in 2002 @Steinbeck2003NMRShiftDB @Steinbeck2004NMRShiftDB. The original system went live in November 2003, and by mid-2004 it held over 10,000 spectra. Primary hosting now resides at the NMR laboratory at the University of Cologne under Nils Schloerer. As of early 2026, the database reports 271,816 structures, 70,029 measured spectra, and 396,583 calculated spectra. In terms of unique experimentally measured entries, the database encompasses approximately 54,000 spectra across roughly 45,000 distinct molecules, covering $""^1$H, $""^(13)$C, $""^(19)$F, and other nuclei. A distinguishing feature is its peer-review mechanism: all submitted datasets are reviewed by a scientific advisory board before inclusion, lending the data a level of reliability uncommon among open chemical databases.

Bulk data exports are distributed via SourceForge in several formats. The NMReDATA SDF file (284 MB) provides the richest representation, encoding assigned spectra in the NMReDATA standard. A signals-annotated SDF (159 MB) and a basic structures-only SDF (139 MB) are also available, along with 3D-coordinate variants and compressed PostgreSQL dumps (1.1 GB). The database is integrated into the NFDI4Chem initiative in Germany, where it serves as a curated NMR data repository component. NMRShiftDB2 has been used extensively as a benchmark dataset for NMR chemical shift prediction algorithms, including hierarchical substructure-based (HOSE code) predictors, graph neural networks, and deep learning approaches, making it the de facto standard reference for evaluating shift prediction accuracy.

=== SDBS <sec-sdbs>

The Spectral Database for Organic Compounds (SDBS) is one of the oldest and most respected freely available spectral reference databases in analytical chemistry, maintained by the National Metrology Institute of Japan (NMIJ) within AIST @Saito2011SDBS @SDBS2025. Research activities underlying SDBS began in 1982, with systematic in-house measurement of authentic spectral data to ensure analytical reliability. Digital access was established in 1989, followed by free public web-based release in 1997. As of March 2025, SDBS catalogs approximately 34,600 organic compounds with six types of spectra: $""^1$H NMR (approximately 15,900 spectra), $""^(13)$C NMR (approximately 14,200 spectra), Fourier-transform infrared (approximately 54,100 spectra), electron ionization mass spectra (approximately 25,000), laser Raman (approximately 3,500), and electron paramagnetic resonance (approximately 2,000). Two-thirds of the compounds have between 6 and 16 carbon atoms, reflecting the focus on commercial organic reagents. All spectra were measured in-house by AIST researchers using calibrated instruments, lending the data exceptionally high reliability.

Despite its scientific value, SDBS presents significant challenges for programmatic data access. The database offers no bulk download mechanism, no public API, and operates exclusively through a web interface that enforces a click-through disclaimer agreement. Session-based access controls and rate limiting further impede automated retrieval. SDBS does not provide SMILES strings for its compounds; instead, it offers compound names, CAS registry numbers, molecular formulae, and InChI identifiers. Resolving these to canonical SMILES requires secondary lookups against external services such as PubChem. For this project, custom scraping infrastructure was developed using Playwright browser automation and direct HTTP requests with parallelized workers to enumerate compound metadata. A fallback lookup to PubChem by CAS number was used to obtain canonical SMILES for compounds lacking InChI in SDBS.

=== NP-MRD <sec-npmrd>

The Natural Products Magnetic Resonance Database (NP-MRD) is the world's largest freely available NMR database dedicated to natural products, maintained by Wishart and collaborators at the University of Alberta with support from NIH @Wishart2025NPMRD. As of its current release, NP-MRD contains 281,859 natural product compounds encompassing small molecules derived from plants, fungi, bacteria, marine organisms, and animals. The database stores over 5.4 million total NMR spectra, of which approximately 19,045 are experimental (18,259 1D and 786 2D), 416,405 are simulated from experimental assignments, and over 5 million are computationally predicted using the CASPRE/PROSPRE prediction engines. Data are distributed in multiple formats including nmrML, JCAMP-DX, raw FID files in Bruker TopSpin format, chemical shift peak lists, and compound metadata in XML and JSON. The full download archive spans well over 100 GB, with the nmrML spectral files alone exceeding 160 GB. NP-MRD integrates data from several partner databases, including HMDB, BMRB, the JEOL CH-NMR-NP collection, and the Natural Products Atlas, with all data released under a CC BY-NC 4.0 license.

NMR data for natural products differ from those of synthetic compounds in several important respects. Natural products typically exhibit far greater structural diversity and stereochemical complexity than synthetic molecules, with extensive ring systems, chiral centers, and unusual functional groups (terpenoids, polyketides, alkaloids, glycosylated metabolites) that produce highly congested and overlapping spectra. Solvent variability is a major practical concern, as natural products are often characterized in CDCl$""_3$, DMSO-_d_$""_6$, CD$""_3$OD, D$""_2$O, or pyridine-_d_$""_5$ depending on solubility. NP-MRD addresses this by storing rich metadata including species of origin, chemical ontology classifications, and literature references for every compound, and by providing DFT-calculated chemical shift predictions within 24 hours of deposition to aid in structure validation. The database also provides ML-predicted $""^1$H and $""^(13)$C spectra at multiple spectrometer frequencies and includes integrated spectral comparison utilities.

=== HMDB <sec-hmdb>

The Human Metabolome Database (HMDB) is the most comprehensive freely available electronic database dedicated to the human metabolome, developed and maintained by the Wishart Research Group at the University of Alberta @Wishart2007HMDB @Wishart2022HMDB. Since its initial release as HMDB 1.0 in 2007 with 2,180 metabolite entries, the database has undergone exponential growth through four major revisions: HMDB 2.0 (2009, 6,800 entries), HMDB 3.0 (2013, 40,153 entries) @Wishart2013HMDB, HMDB 4.0 (2018, 114,100 entries) @Wishart2018HMDB, and the current HMDB 5.0 (2022, 217,920 entries). Beyond metabolite enumeration, HMDB provides extensive chemical, clinical, and molecular biological annotations including chemical taxonomy, physiological concentrations, disease associations, and pathway information.

Of particular relevance to this work, HMDB contains both experimental and computationally predicted NMR spectral data. The experimental NMR collection includes approximately 400 metabolite standards with high-quality $""^1$H and $""^(13)$C NMR spectra acquired under controlled conditions, along with associated raw FID files. HMDB 5.0 substantially expanded its predicted spectral coverage, adding 312,980 predicted $""^1$H and $""^(13)$C NMR spectra computed using density functional theory and machine learning methods. Accessing HMDB data programmatically presents practical challenges: the server employs Cloudflare Web Application Firewall protection that blocks automated HTTP requests, returning 403 Forbidden responses even with browser-mimicking user agents. For this project, the primary metabolite data file (910 MB XML dump with SMILES for all 217,920 entries) was obtained via the Internet Archive's Wayback Machine, along with HMDB 2.5-era NMR archives containing FIDs, peak lists, and processed spectra totaling 2.3 GB.

=== BMRB and GISSMO <sec-bmrb>

The Biological Magnetic Resonance Data Bank (BMRB) was founded in 1988 by Markley and Ulrich at the University of Wisconsin--Madison as the international open-data repository for biomolecular NMR spectroscopy @Hoch2023BMRB. Originally focused on protein and nucleic-acid chemical shifts, BMRB became a core archive of the Worldwide Protein Data Bank in 2007 and now houses over 11 million assigned chemical shifts from more than 15,000 deposited studies. Operations transferred to UConn Health in 2020, though the archive retains deep ties to the National Magnetic Resonance Facility at Madison (NMRFAM). A dedicated metabolomics wing provides experimental time-domain data, reference spectra, and standardized chemical identifiers for more than 1,200 common small-molecule metabolites, making it the primary public resource for NMR-based metabolite identification in biofluids, natural-product screening, and clinical biomarker discovery.

The GISSMO (Guided Ideographic Spin System Model Optimization) library, developed as a collaboration between NMRFAM, NMRBox, and BMRB, extends the metabolomics archive from static peak lists to full quantum-mechanical spin-system parameterizations @Dashti2017GISSMO. For each compound, GISSMO refines a matrix of chemical shifts and scalar coupling constants against an experimental 1D $""^1$H spectrum, then uses that matrix to simulate spectra at 18 magnetic-field strengths spanning 40 to 1,300 MHz. The current library contains more than 1,286 parameterized compounds, including 656 endogenous metabolites, 665 drug-like fragments from the Maybridge Ro3 screening library, and 487 lignin derivatives, with peak lists exported for every simulated spectrum. In the dataset assembled for this work, GISSMO entries were parsed into a relational table keyed on BMRB entry identifier and linked to SMILES strings, yielding approximately 3,315 unique structures and roughly 90,000 individual $""^1$H peak annotations. The spin-system matrices provide a field-strength-independent representation that generalizes across spectrometer configurations.

=== nmrXiv <sec-nmrxiv>

nmrXiv is an open, FAIR-compliant repository for NMR data developed under the NFDI4Chem initiative in Germany @Patil2023nmrXiv. Unlike legacy NMR databases such as SDBS or HMDB, which store only processed peak lists or static spectral images, nmrXiv is designed to host raw, instrument-level NMR data, including original FIDs in vendor-native formats (Bruker, JEOL, Varian) alongside processed spectra in open formats such as JCAMP-DX and NMReDATA. Each deposition is assigned a persistent DOI, machine-readable metadata conforming to Schema.org conventions, and a Creative Commons license, ensuring long-term discoverability and reuse. The platform enforces FAIR principles at the repository level by requiring structured metadata, open-access APIs, and standardized chemical ontologies for compound annotation. As of early 2026, nmrXiv hosts hundreds of curated projects spanning organic, natural-product, and synthetic chemistry.

For the present work, 151 publicly available nmrXiv projects were downloaded programmatically through the platform's REST API, which exposes project, study, and dataset endpoints in JSON format. Each project contains one or more studies, and each study contains one or more datasets corresponding to individual NMR experiments. The API returns download URLs for raw data archives (ZIP files preserving the original directory structure of the spectrometer output), which were retrieved and extracted automatically. This programmatic access contrasts sharply with older repositories such as SDBS, which lack any public API and require manual or browser-automated retrieval. The raw FID data obtained from nmrXiv preserves the full time-domain signal, enabling custom reprocessing pipelines (apodization, Fourier transform, phase correction, baseline correction) rather than relying on pre-processed peak tables whose processing parameters are often undocumented. This level of data fidelity is critical for machine-learning applications where model performance depends on consistent and reproducible spectral preprocessing across the entire training corpus.

=== NMRBank <sec-nmrbank>

NMRBank is a large-scale experimental NMR database constructed through automated text mining of open-access PubMed Central articles using the NMRExtractor pipeline @Wang2025NMRExtractor. The pipeline processes the full-text corpus of 5,734,869 PMC articles in three stages. First, regular expressions identify paragraphs containing NMR data, yielding 380,220 candidate paragraphs from 58,795 articles. Second, a fine-tuned Mistral-7b large language model extracts structured fields from each paragraph, including compound IUPAC names, $""^1$H and $""^(13)$C NMR chemical shifts, experimental conditions, and a confidence score derived from cumulative log-probabilities. The model was trained on 1,000 manually annotated NMR paragraphs and achieves greater than 0.85 extraction accuracy across diverse reporting formats. Third, IUPAC names are converted to canonical SMILES using ChemDraw with OPSIN as a fallback, followed by RDKit standardization. Entries with confidence scores above 0.8 exceed 97% accuracy.

The resulting dataset contains 225,809 entries, of which 156,621 were successfully converted to SMILES representations, corresponding to 149,135 unique molecular structures. The data are distributed as a CSV file with columns for SMILES, $""^1$H and $""^(13)$C chemical shifts as text strings, experimental conditions, confidence scores, and PMC accession numbers linking each entry to its source publication. In the present work, NMRBank serves as a supplementary NMR source after NMRexp and NMRShiftDB2. Chemical shifts are extracted by parsing floating-point values from the text field, providing individual peak positions in ppm. Although the text-mined shifts lack the multiplicity and coupling-constant annotations available in curated databases, NMRBank contributes 149,000 compounds that substantially expand chemical-space coverage, particularly for natural products and pharmaceutical intermediates whose NMR data appear only in the primary literature.

=== Specialized and Emerging Databases <sec-specialized-nmr>

Several smaller or more specialized databases were also evaluated for their potential contributions to the training corpus. Each serves a distinct niche in the NMR data ecosystem, and while none individually approaches the scale of NMRexp or NP-MRD, they collectively illustrate the diversity of data representations and curation philosophies in the field.

*2DNMRGym* is the first large-scale annotated experimental dataset for machine learning on two-dimensional NMR spectra, introduced by Li, Xu, and Hong @Li2025_2DNMRGym. The dataset contains 22,348 heteronuclear single quantum coherence (HSQC) spectra compiled from HMDB and the CH-NMR-NP natural products database, with molecular identifiers cross-referenced against PubChem. Each entry pairs an HSQC cross-peak table with the corresponding molecular graph and SMILES string, with peak positions stored as carbon-index-mapped chemical shift coordinates rather than raw spectral images. A held-out evaluation set of 479 spectra was manually annotated and cross-validated by three domain experts. Two-dimensional NMR techniques such as HSQC spread information across two frequency axes by correlating $""^1$H chemical shifts with those of $""^(13)$C, so that each cross peak encodes a direct one-bond coupling. This additional dimension dramatically reduces spectral congestion and provides atom-level connectivity information absent from 1D spectra.

*PROSPRE* (PROton Shift PREdictor) is a machine-learning web server that predicts $""^1$H NMR chemical shifts for small molecules in four common solvents: D$""_2$O, CDCl$""_3$, DMSO-_d_$""_6$, and CD$""_3$OD @Sajed2024PROSPRE. The underlying graph neural network was trained on 4,207 experimentally measured $""^1$H chemical shifts from 577 curated molecules drawn from HMDB (430 molecules), BMRB (103 molecules), and GISSMO (44 molecules). The predictor achieves a mean absolute error of 0.10 ppm in water and 0.19 ppm in chloroform. PROSPRE's downloadable training and holdout datasets offer a compact but carefully curated resource for benchmarking solvent-correction methods. For downstream applications such as structure--property regression from NMR descriptors, solvent-aware shift predictions allow spectra acquired under different conditions to be harmonized to a common reference frame before featurization.

*The IR-NMR Multimodal Computational Spectra Dataset*, published by Zipoli, Alberts, and Laino of IBM Research Europe, provides computationally generated infrared and NMR spectra for a large set of organic molecules extracted from patent literature @Zipoli2025IRNMR. The dataset contains IR spectra for 177,461 compounds alongside $""^1$H and $""^(13)$C chemical shifts for a subset of 1,255 compounds. Chemical shifts were computed using Car-Parrinello molecular dynamics at the DFT level with the PBE exchange-correlation functional and Goedecker-Teter-Hutter pseudopotentials, then referenced to tetramethylsilane. The NMR parquet file records frame-averaged chemical shifts, raw per-atom shielding tensors, and standard deviations across molecular dynamics frames, providing a uniquely detailed view of conformational averaging effects on chemical shifts.

*The logD-NMR dataset*, curated by Leniak, Pietrus, and Kurczab at Celon Pharma and the Polish Academy of Sciences @Leniak2025logD, takes a fundamentally different approach to NMR data representation. Rather than storing raw spectra or peak lists, the dataset converts each compound's SMILES string to predicted $""^1$H and $""^(13)$C chemical shifts via the NMRShiftDB2 prediction engine, then histograms the resulting shift lists into 200-bin vectors. The dataset contains over 1,200 pharmaceutical compounds with chromatographic hydrophobicity index log _D_ labels measured at three pH conditions (0.26, 7.4, and 10.5). This bucketed pseudo-spectral representation directly demonstrates the use of NMR-derived descriptors as inputs to QSPR models, achieving RMSE values below 0.6 and $Q^2 > 0.7$ using 1D convolutional neural networks on the fused $""^1$H/$""^(13)$C representation.

*The Birmingham Metabolite Library (BML-NMR)* was a publicly accessible database of 1D $""^1$H and 2D $""^1$H J-resolved NMR spectra of 208 authentic metabolite standards @Ludwig2012BML. Each metabolite was prepared at three physiologically relevant pH values (6.6, 7.0, and 7.4), and sixteen NMR spectra were recorded per compound on a 500 MHz spectrometer, encompassing both 1D and 2D experiments with varying acquisition parameters. The resulting 3,328 spectra were stored in a purpose-built MySQL database compliant with Metabolomics Standards Initiative reporting requirements. This systematic variation of pH conditions was particularly valuable because chemical shift positions of ionizable metabolites are pH-dependent. However, the BML-NMR server has been unreachable since approximately September 2025, rendering the full database inaccessible. Despite recovery efforts, only 3 of the 3,328 spectra could be retrieved, representing a near-total loss of this public resource and underscoring the vulnerability of spectral databases hosted on single institutional servers without federated archiving.

=== PubChem as Identifier Resolution Service <sec-pubchem>

PubChem, maintained by the National Center for Biotechnology Information (NCBI), is the world's largest open-access chemical database, containing records for over 116 million unique chemical compounds aggregated from more than 900 data sources @Kim2023PubChem. Each unique chemical structure is assigned a Compound Identifier (CID), a stable integer that serves as a canonical reference. PubChem provides bulk data access through the NCBI FTP server, including the CID-SMILES.gz file (approximately 1.4 GB compressed), which maps every CID to its canonical SMILES string. Alongside SMILES, PubChem provides InChI representations developed by IUPAC and the InChI Trust, offering a layered, non-proprietary canonical identifier suitable for exact-match lookups and cross-database deduplication @Heller2015InChI.

A persistent challenge in cheminformatics is identifier resolution: the same molecule may appear under different names, registry numbers, or structural representations across databases. HMDB, SDBS, and NMRShiftDB2 each use their own internal identifiers, and even ostensibly standard representations such as SMILES can vary between software implementations due to differences in canonicalization algorithms, stereochemistry handling, and aromaticity perception. PubChem addresses this problem by serving as a universal cross-reference hub, with its Identifier Exchange Service and bulk FTP data enabling mapping between CAS Registry Numbers, IUPAC names, InChI, InChIKey, and SMILES through the CID as intermediary. In this work, the CID-SMILES.gz file was used to resolve compound identifiers across heterogeneous NMR spectral databases into a unified canonical SMILES representation, which was subsequently re-canonicalized using RDKit to ensure consistency with the molecular representations used throughout the modeling pipeline @Kim2019PubChem2019. This two-stage canonicalization---first through PubChem and then through RDKit---eliminates ambiguity arising from differing SMILES conventions and enables reliable structure-based joins across datasets that would otherwise lack a common identifier.
