// 03b-data-thermo-fuel — Thermophysical property and fuel-specific databases

The thermophysical property labels used throughout this work were assembled from six complementary sources that collectively span more than 1.2 million experimental data points across thousands of compounds. These sources differ in accuracy, chemical coverage, and data format, but together they provide sufficient breadth and depth to train machine learning models for viscosity, surface tension, and density prediction. @tbl-thermo-summary presents a consolidated overview of each source, including the number of compounds and data points contributed to the training pipeline.

#figure(
  table(
    columns: (2.2fr, 1.2fr, 1.2fr, 2fr),
    align: (left, center, center, left),
    fill: (col, row) => if row == 0 { rgb("#73000A").lighten(85%) },
    [*Source*], [*Compounds*], [*Data Points*], [*Properties*],
    [NIST ThermoML Archive], [~1,272 (pure visc.)], [1,161,660], [Viscosity, surface tension, density (pure + mixture)],
    [`chemicals`/`thermo` Libraries], [~1,042 (visc.)], [~14,750], [Viscosity, surface tension, density, $T_b$, $T_f$],
    [CoolProp Reference Fluids], [124], [~17,360], [Viscosity, surface tension, density, $C_p$, $k$],
    [NIST ILThermo], [1,456], [33,064], [Viscosity, surface tension (ionic liquids)],
    [NIST Chemistry WebBook], [74], [~44,000], [Viscosity, surface tension, density (saturation curve)],
    [Joback Group Contribution], [4,988], [~49,880], [Viscosity, surface tension (estimated)],
    [DDB / UNIFAC Free Tables], [~500], [--], [Group interaction parameters, Antoine coefficients],
  ),
  caption: [Summary of thermophysical property sources. Data point counts include all temperatures and properties extracted from each source. The Joback estimates carry 10--30\% uncertainty and were used for pretraining and data augmentation rather than as ground truth.],
) <tbl-thermo-summary>

=== NIST ThermoML Archive

ThermoML is the IUPAC-standard XML schema for encoding experimentally determined thermodynamic and thermophysical property data, first formalized by Frenkel, Chirico, Diky, Yan, Dong, and Muzny in 2005 @Frenkel2005. The schema captures compound identity (CAS Registry Number, InChI, InChIKey, molecular formula), experimental conditions (temperature, pressure, composition), property values with uncertainties, and metadata on measurement methodology. Each data file maps to a single journal article and encodes one or more pure-or-mixture data blocks, where properties are grouped by type (transport, surface, volumetric) and linked to constraint and variable definitions that specify whether temperature, pressure, or composition was scanned or held fixed. Standard SI units are enforced throughout: viscosity in Pa$dot$s, density in kg\/m#super[3], and surface tension in N\/m. The NIST ThermoML archive, distributed as a 181 MB compressed tarball expanding to approximately 3.9 GB, contains 23,846 JSON-converted files derived from the original XML submissions to five journals from 2003 through 2019: the _Journal of Chemical and Engineering Data_, the _Journal of Chemical Thermodynamics_, _Fluid Phase Equilibria_, the _International Journal of Thermophysics_, and _Thermochimica Acta_ @NISTThermoMLArchive. Because the archive is a product of the U.S. federal government, it carries no copyright restrictions and is released into the public domain.

Parsing the 11,923 files that contain property data yielded 1,161,660 total data points distributed across six categories: pure-compound density (186,394 entries), pure-compound viscosity (44,440 entries from approximately 1,272 unique compounds), pure-compound surface tension (9,175 entries), mixture density (659,550 entries), mixture viscosity (223,807 entries), and mixture surface tension (38,294 entries). The viscosity data span a wide range of chemical classes, from light hydrocarbons and alcohols to heavy polyols and substituted aromatics, with temperatures typically between 273 K and 373 K and pressures at or near atmospheric. For the present work, the pure-compound viscosity and surface tension entries were the primary training targets, while the mixture data were reserved for future mixture-property modeling. Working with ThermoML data requires navigating several practical challenges. The JSON structure is deeply nested, with property types buried inside property group sub-dictionaries, and temperature and pressure may appear as either variable definitions (varying across data points within a block) or constraint definitions (fixed for the entire block), requiring the parser to merge both sources to reconstruct complete state conditions for each measurement. Compound identification relies on InChI strings for SMILES conversion, but a non-trivial fraction of entries contain salts, polymers, or ionic liquids whose InChI cannot be canonicalized to a valid SMILES, reducing the usable compound count. These parsing procedures were implemented in a custom Python script that flattened the nested JSON structures, resolved property types by keyword matching, and exported the results as six CSV files indexed by InChI and InChIKey @Frenkel2006ThermoML @Diky2013TDEJournal.

=== Open-Source Correlation Libraries

The `chemicals` and `thermo` open-source Python libraries, both components of the Chemical Engineering Design Library (ChEDL) developed by Caleb Bell, served as the primary source of computed thermophysical properties for compounds lacking direct experimental measurements @Bell2025chemicals @Bell2025thermo. The `chemicals` library provides low-level access to pure-component property correlations drawn from standard references including Perry's Chemical Engineers' Handbook @Green2019, the VDI Heat Atlas @VDI2010, and the DIPPR evaluated-data compilations. For liquid viscosity, the library implements several temperature-dependent models: DIPPR Equation 101 (a four-parameter exponential form covering 337 compounds from Perry's Table 2-313), three variants of the Viswanath--Natarajan correlation (432 compounds in the three-term form), the Dutt--Prasad three-term correlation (100 compounds), and VDI PPDS polynomial fits (271 compounds). For surface tension, available correlations include the Jasper--Lange linear model (522 compounds), VDI PPDS Series 11 coefficients (272 compounds), and the Mulero--Cachadina formulation (115 compounds). Across all correlation sources, approximately 1,042 unique compounds have at least one viscosity correlation available, and approximately 690 compounds have surface tension data. The higher-level `thermo` library wraps these correlations with automatic method selection and ranking, choosing the best available data source for each compound at the requested temperature and pressure. Using these libraries, viscosity and surface tension values were evaluated at ten temperatures spanning each compound's liquid range, producing a computed-property dataset of approximately 7,860 viscosity and 6,890 surface tension evaluations.

For a smaller set of high-accuracy reference fluids, properties were obtained from CoolProp, an open-source C++ library with Python bindings that implements multiparameter Helmholtz energy equations of state @Bell2014CoolProp. CoolProp covers 124 pure and pseudo-pure fluids whose thermodynamic and transport properties are computed from reference-quality correlations validated against primary experimental data. Because Helmholtz-based formulations provide internally consistent thermodynamic surfaces, CoolProp yields lower uncertainty than empirical fits for the fluids it supports, typically sub-percent for density and 1--3\% for viscosity and surface tension along the saturation curve. In this work, CoolProp contributed viscosity, surface tension, density, thermal conductivity, heat capacity, vapor pressure, and enthalpy of vaporization for all 124 fluids at 20 temperatures each, yielding approximately 17,360 property evaluations that serve as high-fidelity anchor points for model calibration. Together, these three libraries---`chemicals`, `thermo`, and CoolProp---enabled the construction of a computed-property dataset spanning over 1,000 compounds without requiring access to proprietary databases such as DIPPR 801. All property evaluations are deterministic and reproducible given a compound identifier (CAS number or SMILES) and the library version.

=== NIST ILThermo

The NIST Standard Reference Database 147, known as the Ionic Liquids Thermodynamics Database or ILThermo, is a critically evaluated repository of experimental thermophysical property data for ionic liquids maintained by the Thermodynamics Research Center at the National Institute of Standards and Technology @Dong2007 @Kazakov2012. Ionic liquids---salts that are liquid at or near room temperature, typically composed of a bulky organic cation paired with an inorganic or organic anion---exhibit negligible vapor pressure, wide liquid ranges, high thermal stability, and tunable physicochemical properties that have attracted intense research interest in applications ranging from electrochemistry and catalysis to carbon capture and lubrication @Welton1999. ILThermo version 2.0 provides a REST API that returns structured JSON data for programmatic queries by property type, chemical identity, author, or keyword. In this work, the API was queried for all single-component viscosity and surface tension datasets, yielding 1,456 unique ionic liquid compounds and 33,064 data points in total: 1,345 compounds with 26,189 viscosity measurements and 506 compounds with 6,875 surface tension measurements. Each dataset was fetched individually with a 0.3-second delay between requests to avoid overloading the server, and the returned values were converted to common engineering units (mPa$dot$s for viscosity, mN\/m for surface tension).

Ionic liquid data from ILThermo serve a distinct and complementary role relative to the organic compound datasets that form the bulk of the training corpus. Conventional organic liquids in the ThermoML and `chemicals` databases are predominantly small neutral molecules---hydrocarbons, alcohols, esters, and ethers with molecular weights below 300 g\/mol---whose viscosities at room temperature typically fall between 0.3 and 10 mPa$dot$s and whose surface tensions range between 15 and 40 mN\/m. Ionic liquids, by contrast, exhibit viscosities that are one to three orders of magnitude higher, commonly 30 to 500 mPa$dot$s at 298 K with some exceeding 10,000 mPa$dot$s, and surface tensions that cluster between 25 and 50 mN\/m owing to their strong Coulombic cohesion. Including ionic liquids in the training set therefore extends the dynamic range of the viscosity target by roughly two orders of magnitude, which improves model extrapolation to highly viscous organic liquids and fuel blends at low temperatures. Furthermore, ionic liquids introduce structural motifs---imidazolium, pyridinium, pyrrolidinium, and phosphonium cations paired with fluorinated or cyano anions---that are absent from conventional organic datasets, encouraging the model to learn more generalizable structure--property relationships rather than overfitting to the narrow chemical space of light hydrocarbons.

=== NIST Chemistry WebBook and CoolProp Reference Fluids

The NIST Chemistry WebBook (Standard Reference Database 69) provides thermophysical property data for 74 reference fluids computed from validated Helmholtz-energy equations of state, representing the highest-fidelity data in this collection @Linstrom2023. For each fluid, the WebBook supplies liquid-phase viscosity, surface tension, and density along the saturation curve at 1 K increments from the triple point to the critical point, yielding approximately 600 data points per compound and roughly 44,000 data points in aggregate across the 74 fluids. Although small in chemical scope---the 74 fluids are predominantly light hydrocarbons, refrigerants, and common industrial solvents---these data carry sub-percent uncertainties for density and 1--3\% uncertainties for viscosity and surface tension, making them suitable as ground-truth benchmarks for evaluating model accuracy. The WebBook data were scraped from the NIST Fluid Properties interface using automated HTTP requests, and each fluid's saturation-curve data were exported as a CSV file with columns for temperature, viscosity, surface tension, and density. A master index consolidating all 74 fluids was compiled for rapid cross-referencing.

=== Dortmund Data Bank Free Tables

The Dortmund Data Bank (DDB), maintained by DDBST GmbH, is one of the world's largest collections of thermodynamic and transport property data for pure compounds and mixtures @Gmehling2002. Although the full DDB is a commercial product, DDBST publishes a subset of group-interaction parameters and reference data on its public website. In this work, three categories of free DDB data were incorporated: UNIFAC group-interaction parameters for activity-coefficient estimation, Antoine vapor-pressure coefficients for several hundred compounds, and phase-change enthalpies. The UNIFAC parameters are particularly valuable because they enable the UNIFAC-VISCO mixture viscosity method @Cao1993, which decomposes mixture transport properties into combinatorial and residual contributions using the same functional-group framework employed in vapor--liquid equilibrium calculations @Fredenslund1975. Additionally, Antoine coefficients from the DDB free tables were used for vapor-pressure calculations needed in corresponding-states viscosity and surface tension correlations. Six supplementary files scraped from the NIST Chemistry WebBook provided Antoine parameters, phase-change data, and thermochemical properties for 94 common C#sub[5]--C#sub[20] hydrocarbons relevant to jet fuel applications.

=== Group Contribution Estimates

To extend property coverage beyond the approximately 1,300 compounds for which experimental or high-quality correlation data were available, group contribution estimates were computed for 4,988 compounds sampled from the NMRexp SMILES pool using the Joback method @Joback1987. The Joback method estimates critical temperature, critical pressure, and normal boiling point from additive contributions of 41 first-order molecular substructures identified by SMARTS pattern matching in RDKit @Landrum2024RDKit. These critical properties were then fed into corresponding-states correlations: the Letsou--Stiel method for viscosity and the Brock--Bird method for surface tension @Poling2001. Property values were generated at five temperatures (250, 300, 350, 400, and 450 K), yielding approximately 24,940 viscosity estimates and 24,940 surface tension estimates. These group contribution values carry typical errors of 10--30\% for hydrocarbons and larger errors for polar or multifunctional compounds, so they were used exclusively for model pretraining and data augmentation rather than as ground-truth labels. The pretraining strategy exposes the model to a broader chemical space during initial weight optimization, after which the model is fine-tuned on the smaller but more accurate experimental datasets from ThermoML and the `chemicals` library.

Separately, the `chemicals` library was used to generate expanded property evaluations for its approximately 786 viscosity compounds and 689 surface tension compounds at ten temperatures each, using the best available correlation for each compound as selected by the `thermo` ranking algorithm. Density data were generated for approximately 441 compounds using Perry's DIPPR Equation 105 and VDI PPDS polynomial correlations, producing 8,718 density data points that were supplemented by the 44,000 NIST WebBook density values to create a combined density training set spanning roughly 500 compounds. Thermal conductivity (101,333 data points across 9,861 compounds) and heat capacity (101,361 data points across 9,861 compounds) were also generated as multi-task learning targets, providing auxiliary regression objectives that share molecular representations with the primary viscosity and surface tension tasks.

=== Identifier Reconciliation

Merging data across these six sources presented a persistent identifier-reconciliation challenge that warrants explicit discussion. The NIST Chemistry WebBook uses internal alphanumeric codes, ThermoML records carry CAS Registry Numbers and InChI strings, the `chemicals` library indexes primarily by CAS number, ILThermo uses compound names and molecular formulas, and the NMR spectral databases (NMRexp and NMRShiftDB2, described in the preceding section) use SMILES as their primary key. Linking records across sources required converting between CAS, InChI, InChIKey, and canonical SMILES through a combination of PubChem API lookups, the `chemicals.identifiers.search_chemical` function, and RDKit canonicalization @Kim2023PubChem. This process introduced occasional mismatches for stereoisomers (where CAS distinguishes _cis_ and _trans_ forms but canonical SMILES may not), for salts and hydrates (where InChI encodes the complete stoichiometry but SMILES typically represents only the organic component), and for compounds absent from PubChem. To mitigate these errors, all merged datasets were filtered by molecular-weight consistency checks---rejecting any cross-reference where the molecular weights implied by the two identifiers differed by more than 1 g\/mol---and, where possible, validated against the original compound names stored in the source databases. The final unified compound index, stored as a master CSV file mapping CAS, InChI, InChIKey, SMILES, name, and molecular formula, contains 1,225 compounds for which all identifier types were successfully reconciled and at least one thermophysical property and one molecular representation (fingerprint, descriptor, or NMR spectrum) are available.
