// 03c-data-fuel-specific — Fuel-Specific Data

=== AFRL Jet Fuel Property Compilation <afrl-data>

The primary source of fuel-mixture ground truth in this work is the AFRL technical report AFRL-RQ-WP-TR-2020-0017, authored by Edwards and published in January 2020 @Edwards2020. This 136-page document constitutes the most comprehensive publicly available compilation of thermophysical properties for both conventional petroleum-derived and alternative jet fuels. Edwards catalogues properties for three Category A reference fuels---JP-8 (POSF 10264), Jet-A (POSF 10325), and JP-5 (POSF 10289)---alongside more than ten alternative fuels, including Shell SPK (POSF 5729), Sasol IPK (POSF 7629), Syntroleum S-8 (POSF 5018), UOP camelina HEFA (POSF 10301), Gevo ATJ (POSF 11498), and several others. Each fuel is identified by its POSF (Properties of Fuels) tracking number, a unique integer assigned by the AFRL Fuels and Energy Branch to every fuel sample that enters the characterization pipeline.

The report is distributed as thirteen CSV files, each corresponding to a different property or property class. Tabulated quantities include density, dynamic viscosity, surface tension, speed of sound, bulk modulus, lubricity, distillation curves, derived cetane number, flash point, freeze point, net heat of combustion, hydrogen content, and molecular weight distributions. Temperature-dependent data are provided where available: density--temperature linear equations derived from the CRC Handbook and the Department of Defense World Fuel Survey, viscosity at $-20 degree.c$ and $-40 degree.c$, and surface tension as a function of temperature with linear-fit coefficients. Detailed GC$times$GC hydrocarbon-class composition breakdowns enable composition-weighted property modeling of real fuel mixtures. Of particular value to this work are the low-temperature viscosity measurements for alternative fuels, the surface tension linear regressions, and the GC$times$GC composition data that supply the mole fractions needed to aggregate pure-compound predictions into fuel-level estimates.

Six fuels from the Edwards compilation serve as the validation set throughout Phases 3 and 4 of this study. @fuel-validation-table summarizes these fuels together with the POSF identifiers and measured property ranges used for model evaluation.

#figure(
  table(
    columns: (auto, auto, auto, auto),
    align: (left, center, center, center),
    table.header(
      [*Fuel*], [*POSF*], [*Type*], [*Primary Use*],
    ),
    [JP-5], [10289], [Petroleum], [Navy / carrier ops],
    [Jet-A], [10325], [Petroleum], [Commercial aviation],
    [HRJ-Camelina], [7720], [HEFA], [Bio-derived SAF],
    [Shell SPK], [5729], [Fischer--Tropsch], [Synthetic paraffinic],
    [Sasol IPK], [7629], [Fischer--Tropsch], [Iso-paraffinic],
    [Gevo ATJ], [10151], [Alcohol-to-jet], [Bio-derived SAF],
  ),
  caption: [Six validation fuels drawn from the AFRL compilation @Edwards2020, spanning petroleum baselines and four distinct alternative-fuel production pathways.],
) <fuel-validation-table>

These six fuels span the compositional diversity of the current jet fuel landscape. The two petroleum-derived fuels, JP-5 and Jet-A, are complex mixtures of hundreds of hydrocarbons across the $"C"_8$--$"C"_16$ range, containing normal and branched paraffins, cycloparaffins, and aromatics. The four alternative fuels, by contrast, are enriched in specific hydrocarbon classes depending on their synthesis pathway: the Fischer--Tropsch fuels (Shell SPK and Sasol IPK) are predominantly iso-paraffinic with negligible aromatic content, the HEFA fuel (HRJ-Camelina) retains some cycloparaffinic character from its bio-feedstock, and the alcohol-to-jet fuel (Gevo ATJ) is a narrow-cut iso-paraffinic kerosene. This diversity provides a stringent test of whether models trained on pure-compound data can generalize to fuel mixtures whose compositions differ markedly from one another.

=== Burnett Reference Implementation <burnett-data>

The modeling architecture and featurization strategy in this work build upon a reference implementation by Burnett, released as an open-source repository under the GNU General Public License v3 @Burnett2024NMRProperty. Burnett provides two parallel neural network pipelines for predicting the temperature-dependent viscosity of pure hydrocarbons. The first pipeline takes simulated proton NMR spectra as input: SMILES strings for each training compound are submitted to the NMReDB spectral prediction service, which returns chemical shift positions and hydrogen multiplicities that are convolved with Lorentzian line shapes to produce a continuous $""^1"H"$ spectrum discretized at 6554 points. These spectra are fed into a four-layer one-dimensional convolutional neural network with 32, 16, 8, and 4 filters, followed by three fully connected layers (128, 64, and 2 neurons), which outputs two Arrhenius-type coefficients $A$ and $B$ such that $ln eta = A + B slash T$.

The second pipeline replaces the NMR spectrum with a seven-element functional group vector counting CH#sub[3], CH#sub[2], CH, quaternary C, aromatic ring, cyclic CH#sub[2], and long-chain CH#sub[2] groups, identified by SMARTS substructure matching through RDKit. This vector is processed by a compact three-layer fully connected network (12, 4, and 2 neurons). Both pipelines are trained on approximately 65 pure hydrocarbons whose experimental viscosity--temperature data are drawn from the NIST ThermoData Engine via ThermoML-format equations. The training set spans normal alkanes, branched alkanes, cycloalkanes, and aromatics representative of jet fuel constituents, providing coverage of the major hydrocarbon families present in the AFRL fuels. Burnett further demonstrates fuel-mixture prediction by applying the trained models to JP-5 (POSF 10289), Jet-A (POSF 10325), and HRJ-Camelina (POSF 7720) using composition-weighted averages of constituent pure-compound predictions. This composition-weighted aggregation strategy is adopted directly in the present work and extended to surface tension and density.

=== NMR-Based Fuel Property Prediction Literature <jameel-parker-data>

Two independent lines of published research establish the precedent that NMR spectra encode sufficient chemical information for quantitative fuel property prediction. Abdul Jameel et al. demonstrated that seven functional group abundances extracted from $""^1"H"$ NMR spectra---paraffinic CH#sub[3], paraffinic CH#sub[2], paraffinic CH, olefinic CH=CH#sub[2], naphthenic CH--CH#sub[2], aromatic C--CH, and ethanolic OH---together with molecular weight and a branching index, suffice to predict research and motor octane numbers with $R^2 = 0.99$ and mean absolute errors of approximately 1.2 octane numbers @AbdulJameel2018Octane. That study compiled data for 128 pure hydrocarbons, 123 hydrocarbon--ethanol blends of known composition, and 30 FACE (Fuels for Advanced Combustion Engines) gasoline--ethanol blends. In a subsequent paper, Abdul Jameel formalized the spectral integration procedure by defining precise chemical shift windows for six hydrocarbon functional groups and introduced a branching index parameter that captures the degree of methyl substitution on the carbon backbone @AbdulJameel2021Gasoline. Applied to a dataset of 281 fuels comprising pure compounds and complex blends, this methodology codified a reproducible, standardized protocol for translating $""^1"H"$ NMR spectra of complex fuel mixtures into a compact functional group representation suitable for machine learning.

Parker et al. extended NMR-based fuel property prediction from combustion metrics to thermophysical properties directly relevant to sustainable aviation fuel certification @Parker2025DensityST. Using $""^1"H"$--$""^(13)"C"$ HSQC two-dimensional NMR spectroscopy, the authors identified and quantified discrete atom types---a finer-grained decomposition than the functional groups used by Abdul Jameel---by integrating peaks on the $""^1"H"$ spectrum with carbon-type assignments from the HSQC dimension. Multilinear regression models built on these atom-type group contributions predicted liquid density within 0.00--5.59% absolute error and surface tension within 0.29--4.41% absolute error across six real aviation fuels. The approach is designed to support prescreening under ASTM D4054, where candidate SAFs must demonstrate acceptable thermophysical properties before proceeding to costly engine testing. By requiring only milligram-scale fuel samples and a single NMR measurement, the method offers a rapid, low-cost alternative to conventional ASTM property tests.

Collectively, the progression from Abdul Jameel's octane-number models through Parker's density and surface tension predictions demonstrates that NMR spectroscopy provides a general-purpose analytical framework for fuel property prediction. The same spectral measurement can be reprocessed to target different properties as modeling objectives change. The present work builds on this foundation by replacing multilinear regression with deep learning architectures (Phases 1--2), extending the target properties to include temperature-dependent viscosity, and introducing a composition-weighted aggregation scheme (Phase 3) that enables fuel-mixture prediction from pure-compound models without requiring mixture-level training data.
