// 06-discussion.typ — Discussion

The results across all four phases of this work converge on several conclusions about the strengths, limitations, and future directions of NMR-based thermophysical property prediction. This section interprets the key findings, examines the failure modes encountered, and identifies the practical requirements for deploying NMR-based models in a fuel qualification context.


== What NMR Spectra Encode and What They Miss <discussion-encoding>

The most consistent finding across all experiments is the asymmetry between surface tension and viscosity prediction. Surface tension models achieved hydrocarbon $R^2$ values exceeding 0.81 with NMR features combined with molecular descriptors in Phase 2, and fuel-level surface tension predictions reached MAPE values as low as 1.9% for Shell-SPK and 3.0% for Gevo-ATJ using the NMR spectrum representation in Phase 3. Viscosity, by contrast, proved far more difficult. The best pure-compound viscosity model in Phase 1 achieved a mean hydrocarbon $R^2$ of only 0.70 across five folds even with molecular fingerprints that encode molecular weight, branching, and ring topology. NMR spectra alone performed substantially worse, with the Phase 2 NMR-only XGBoost model yielding negative $R^2$ values on multiple viscosity folds.

This disparity has a clear physical explanation. Surface tension is dominated by intermolecular interactions at the liquid--air interface and scales approximately linearly with temperature for hydrocarbons. The functional group inventory encoded in a $""^1"H"$ NMR spectrum, which directly quantifies aromatic, olefinic, and aliphatic content, captures the essential determinants of these interfacial forces @Parker2025DensityST. Viscosity, however, depends on the resistance to molecular rearrangement within the bulk liquid, which is exponentially sensitive to temperature through the Arrhenius relationship $ln eta = A + B slash T$. The pre-exponential factor $A$ and the activation energy parameter $B$ both depend strongly on molecular weight, chain length, and branching patterns that NMR chemical shifts encode only indirectly. A methylene peak at 1.3 ppm reports the presence of $"CH"_2$ groups but does not distinguish a $"C"_10$ chain from a $"C"_20$ chain. Because viscosity scales roughly as a power law with molecular weight @Poling2001, this ambiguity is catastrophic for viscosity prediction.

The combined NMR-plus-fingerprint representation in Phase 2 achieved HC $R^2 = 0.694$ for viscosity and $R^2 = 0.813$ for surface tension with XGBoost, matching but not exceeding the fingerprint-only baseline. This parity indicates that when molecular structure is known (as it must be to compute fingerprints), NMR features contribute no additional information beyond what the fingerprints already encode. The practical value of NMR emerges only in the mixture regime where molecular structure is unknown, motivating the transition to Phases 3 and 4.


== Transfer Learning: Promise and Distribution Shift <discussion-transfer>

The Phase 4 transfer learning experiments tested whether pretraining on a large corpus of NMR--descriptor pairs could compensate for the small number of compounds with both NMR spectra and measured viscosity. The pretraining dataset contained 296,000 compounds from the NMRexp database @Wang2025NMRexp, for which molecular descriptors were computed from SMILES structures. A multilayer perceptron trained on this corpus learned a general mapping from NMR features to molecular descriptors, which could then serve as a feature extractor for downstream viscosity prediction.

The direct application of the pretrained MLP to viscosity compounds failed, producing an average fuel MAPE of 44.9% in Phase 4 v2, worse than the 39.4% achieved by the simpler Phase 4 v1 XGBoost pipeline. The failure had a straightforward cause. The NMRexp database is dominated by drug-like molecules containing nitrogen, oxygen, sulfur, and halogen substituents, while the viscosity training set consists almost exclusively of hydrocarbons containing only carbon and hydrogen. The descriptor distributions learned during pretraining reflected this drug-like bias, and the model produced systematically incorrect descriptor estimates when applied to hydrocarbon inputs. The pretrained model predicted nonzero topological polar surface area for pure alkanes and achieved $R^2 = -0.99$ for molecular weight prediction on the viscosity compounds, meaning its predictions were worse than simply predicting the mean. This is a canonical example of distribution shift in transfer learning: the source domain (drug-like organic molecules) and target domain (hydrocarbon fuels) share the same input modality (NMR features) but occupy different regions of chemical space.

Fine-tuning the pretrained MLP on the 943 viscosity compounds in Phase 4 v3 reduced the average fuel MAPE from 39.4% to 29.3%, a 26% relative improvement over the non-pretrained baseline. This result demonstrates that transfer learning can extract useful representations from large NMR databases even when the domain mismatch is severe, provided that a fine-tuning step adapts the learned features to the target chemical space. The pretrained weights gave the model an informed initialization that captured general NMR--structure correlations, and fine-tuning on the small but domain-relevant viscosity dataset refined those weights to the hydrocarbon regime.

The improvement is meaningful but bounded by the fundamental scarcity of hydrocarbon--NMR--viscosity intersections in existing databases. The 943 compounds with both NMR spectra and viscosity measurements span a narrow range of hydrocarbon classes, predominantly normal alkanes, branched alkanes, and single-ring aromatics. Polycyclic naphthenes, multi-ring aromatics, and the heterogeneous mixture of structural types found in real jet fuels remain underrepresented.


== The Data Bottleneck <discussion-bottleneck>

The most consequential finding of this work is not any individual model result but the severity of the data bottleneck at the intersection of NMR spectra and thermophysical measurements. The union of all NMR sources surveyed in @nmr-databases contains approximately 1.8 million unique compounds, and the union of all viscosity sources in @thermo-databases contains approximately 2,238 unique compounds. The intersection is 1,330 compounds, which after filtering for valid NMR features and reasonable property ranges yields only 953 training compounds contributing 10,633 measurement rows. Of these, only 355 measurements fall below 260 K, precisely the temperature range that matters most for jet fuel pumpability at altitude.

This bottleneck is not merely a matter of scale but of distribution. The 953 overlap compounds are dominated by polar, drug-like molecules from pharmaceutical and metabolomics literature, because these fields generate the majority of NMR data deposited in public repositories. Simple hydrocarbons, which constitute the entirety of aviation fuel composition, represent only a small fraction of the overlap set. This distributional mismatch creates an extrapolation problem that no amount of architectural sophistication can fully overcome: a model trained predominantly on oxygenated and nitrogen-containing aromatics will struggle to predict properties of saturated alkanes and cycloalkanes, regardless of how expressive its functional form.

Three specific gaps are responsible. First, NMR databases contain few simple hydrocarbons because these compounds hold limited interest for the pharmaceutical and metabolomics communities that generate most public NMR data. NMRexp, the largest open NMR database at 1.48 million compounds, draws from supporting information PDFs in the biomedical literature, where hydrocarbons are underrepresented @Wang2025NMRexp. Second, viscosity databases have limited coverage below 260 K because standard viscometric methods become increasingly difficult at cryogenic temperatures. The ThermoML archive, while containing over 44,000 pure-compound viscosity points, concentrates most of its data between 273 K and 373 K @Frenkel2006ThermoML. Third, the two-stage architecture used in Phase 4 introduces compounding errors: any inaccuracy in Stage 1 descriptor prediction propagates into and is amplified by Stage 2 viscosity regression, a problem that becomes more severe when the Stage 1 model operates outside its training distribution.


== The Cold-Temperature Extrapolation Problem <discussion-cold>

The ASTM D1655 specification sets a maximum viscosity of 8.0 mm$""^2$/s at $-20 degree.c$ (253.15 K) for Jet A and at $-40 degree.c$ (233.15 K) for Jet A-1 @ASTMD1655. Predicting viscosity at these cold temperatures is therefore the most practically relevant capability for fuel screening, and it is precisely where the models perform worst. Phase 3 fuel predictions at 233 K showed dramatic underestimates across all NMR representations. For Gevo-ATJ (POSF 10151), the measured viscosity at 233 K was 10.5 cSt while the NMR spectrum model predicted 0.87 cSt, an error exceeding 90%. For HRJ-Camelina (POSF 7720), the measured value was 11.4 cSt versus a prediction of 1.06 cSt. In every case the model catastrophically underestimated the viscosity at the specification-critical temperature while performing reasonably at 253 K, where predictions fell within 10--50% of measured values.

The root cause is data scarcity at low temperatures compounded by the nonlinear nature of the Arrhenius extrapolation. The training set contains only 14 compounds with viscosity measurements below 240 K. The Arrhenius parameterization $ln eta = A + B slash T$ amplifies prediction errors at low temperatures because the $B slash T$ term grows as $T$ decreases. A 10% error in the estimated $B$ parameter produces a 10% error in $ln eta$ at 300 K but a 13% error at 233 K, and because viscosity is the exponential of $ln eta$, these errors compound multiplicatively in real units. The cold-temperature problem is not unique to NMR-based models. Any data-driven approach trained predominantly on measurements between 280 and 370 K will fail to extrapolate the Arrhenius curve into the 220--250 K regime. The distinction between interpolation and extrapolation is fundamental and cannot be resolved by improving the molecular representation or the model architecture alone. Resolving this limitation requires either collecting substantially more cold-temperature viscosity data for NMR-characterized hydrocarbons or incorporating physics-based constraints that enforce the correct asymptotic behavior at low temperatures.


== Pure Compounds versus Fuel Mixtures <discussion-mixtures>

All models developed in Phases 1 through 4 were trained on pure-compound data and applied to fuel mixtures by treating the mixture NMR spectrum as if it arose from a single compound. This approximation is physically unjustified. A jet fuel typically contains hundreds of individual hydrocarbon species spanning a molecular weight range from roughly $"C"_8$ to $"C"_16$, with each species contributing to the bulk NMR spectrum in proportion to its mole fraction @Edwards2017 @Colket2017. The measured NMR spectrum of a fuel is the mole-fraction-weighted superposition of hundreds of individual spectra @Cookson1987 @FlowerSaxena2005.

When a model trained on pure compounds receives this superposition as input, it interprets the composite functional group distribution as belonging to a single hypothetical molecule. For surface tension, which depends primarily on the functional group inventory and varies modestly with molecular weight, this single-compound approximation works surprisingly well. The Phase 3 results confirm this: surface tension predictions for five reference fuels achieved MAPE values between 1.9% (Shell-SPK) and 12.9% (Jet-A POSF 10325), with the best results for Fischer-Tropsch and hydroprocessed fuels that have relatively narrow compositional distributions. These SPK-type fuels are predominantly isoparaffinic, so their NMR spectra more closely resemble those of individual compounds than do the spectra of conventional petroleum-derived fuels.

For viscosity, the mixture approximation is far more damaging. Viscosity is a nonlinear function of composition that depends on intermolecular interactions between dissimilar species. The viscosity of a binary mixture of $n$-octane and $n$-hexadecane, for example, is not the mole-fraction average of the two pure-component viscosities. Well-established mixing rules exist @Poling2001, but they require knowing the identities and concentrations of the individual components, information that is lost when the model receives only the composite NMR spectrum. The consistently high MAPE values for fuel viscosity prediction, even after transfer learning, likely reflect this fundamental mismatch between pure-compound training and mixture-level inference at least as much as they reflect shortcomings in the NMR features themselves.


== Comparison to Prior Work <discussion-comparison>

The results of this work can be situated within the broader landscape of NMR-based fuel property prediction. Abdul Jameel et al. demonstrated that NMR functional group features can predict octane numbers and ignition quality of gasoline-range fuels with MAPEs below 5% @AbdulJameel2018Octane @AbdulJameel2018MFG. Parker et al. extended this approach to density and surface tension for aviation fuels, achieving strong results using NMR atom type descriptors @Parker2025DensityST. The present work's Phase 3 surface tension results are consistent with these precedents, with MAPEs between 1.9% and 12.9%, confirming that NMR functional group decomposition captures sufficient information for properties governed by intermolecular interactions at the liquid-vapor interface.

The viscosity results, however, reveal a fundamental difference between viscosity and the properties studied in prior NMR-fuel work. Octane number, cetane number, and even surface tension depend primarily on the types of chemical bonds present in the fuel, information that is directly encoded in the chemical shift distribution. Viscosity, by contrast, depends strongly on molecular weight, chain length, and intermolecular entanglement, properties that are only indirectly reflected in the $""^1"H"$ NMR spectrum. The molecular weight bottleneck identified in Phase 2 has not been explicitly noted in prior NMR-fuel studies, likely because those studies focused on properties for which molecular size is a secondary factor.

For pure-compound viscosity prediction from molecular structure, recent machine learning approaches using graph neural networks have achieved $R^2$ values exceeding 0.90 on curated datasets @Bilodeau2024Advancing. The Phase 1 baseline of $R^2 = 0.638$ falls below this ceiling, reflecting both the heterogeneity of the training data (which spans ionic liquids to light hydrocarbons) and the use of fixed fingerprints rather than learned molecular representations. The Phase 2 combined model ($R^2 = 0.694$ for HC viscosity) narrows the gap but does not close it, consistent with the finding that NMR features provide complementary rather than superior information when molecular structure is known.


== Implications for Fuel Screening <discussion-implications>

Despite the 29.3% average MAPE achieved by the best Phase 4 model, the current pipeline does not meet the accuracy requirements for fuel certification, where viscosity errors below 5--10% are typically required to ensure compliance with ASTM D1655 specifications @ASTMD1655. However, the pipeline may still be useful as a first-pass screening tool in the early stages of SAF qualification. In the Tier 1 screening phase of the ASTM D4054 evaluation process, the goal is to identify candidate fuels that are clearly unsuitable, not to provide specification-grade property estimates @ASTMD4054. A model that predicts viscosity to within 30% could reliably flag fuels whose viscosity is more than a factor of two outside specification limits, eliminating obviously unsuitable candidates and reserving expensive laboratory testing for the most promising formulations.

The practical workflow would proceed as follows. A candidate SAF sample undergoes a single $""^1"H"$ NMR measurement requiring fewer than five minutes and microliters of material. The spectrum is processed through the feature extraction pipeline to produce a 120-dimensional descriptor vector. The fine-tuned MLP predicts molecular descriptors from these NMR features, and the Stage 2 XGBoost model predicts viscosity across the temperature range of interest. Candidates whose predicted viscosity curves fall within a conservative tolerance band around the specification limit proceed to physical testing; those outside are deprioritized. This workflow compresses the initial screening from days of laboratory viscometry to minutes of computational prediction.

The value of NMR as a screening measurement extends beyond prediction accuracy. An NMR spectrum is acquired non-destructively, requires minimal sample preparation, and produces a permanent digital record that can be compared against reference databases, reanalyzed as models improve, and shared across laboratories in standardized formats @Hoch2023BMRB @Patil2023nmrXiv. These operational advantages mean that NMR-based screening could be integrated into the earliest stages of SAF development, where hundreds of candidate blends may need to be evaluated rapidly and only a handful will proceed to full ASTM D4054 testing.


== What Would Improve Results <discussion-improvements>

The analysis across all four phases points to three specific investments that would most substantially improve NMR-based fuel property prediction.

First, the single most impactful intervention would be collecting experimental viscosity measurements at temperatures between 220 and 260 K for a targeted set of hydrocarbons that already have NMR spectra in existing databases. The current training set contains only 14 compounds with data below 240 K, which is wholly insufficient to learn the steep viscosity upturn that governs specification compliance. A focused measurement campaign covering 50 to 100 representative hydrocarbons, spanning normal alkanes, isoparaffins, cycloparaffins, and mono- and polycyclic aromatics, would fill the gap that currently makes cold-temperature prediction impossible. The compounds should be selected to maximize coverage of the hydrocarbon structural space relevant to jet fuels while prioritizing species already present in HMDB @Wishart2022HMDB, NMRexp @Wang2025NMRexp, or SDBS @SDBS2025 so that high-quality experimental NMR spectra are already available.

Second, collecting NMR spectra of fuel mixtures with simultaneously measured viscosity and surface tension would directly address the pure-compound-to-mixture transfer problem. Rather than training on pure compounds and hoping that the model generalizes to superposed spectra, a model trained on mixture NMR spectra paired with mixture property measurements would learn the correct composition--property relationship without requiring deconvolution of individual components. The NJFCP reference fuel set @Colket2017 @Edwards2017 provides a natural starting point, as these fuels have extensive property characterization and several already have published NMR spectra. Expanding this dataset to include SAF blends at various blend ratios would create a training corpus directly relevant to the fuel qualification task.

Third, developing mixture-aware model architectures that explicitly account for spectral superposition would address the conceptual mismatch between pure-compound training and mixture inference. One approach would decompose the mixture spectrum into component contributions using NMR deconvolution methods, estimate pure-component properties for each identified species, and combine them using established mixing rules. An alternative would train end-to-end on mixture spectra, bypassing the deconvolution step entirely but requiring a sufficiently large training corpus of mixture NMR spectra paired with measured properties. Both approaches represent a substantial advance over the current single-compound approximation and would bring the modeling framework into alignment with the physical reality of multi-component fuel systems.
