// 06-discussion.typ — Discussion

The results across all four phases of this work converge on several conclusions about the strengths, limitations, and future directions of NMR-based thermophysical property prediction. This section interprets the key findings, examines the failure modes encountered, and identifies the practical requirements for deploying NMR-based models in a fuel qualification context.


== What NMR Spectra Encode and What They Miss <discussion-encoding>

The most consistent finding across all experiments is the asymmetry between surface tension and viscosity prediction. Surface tension models achieved hydrocarbon $R^2$ values exceeding 0.81 with NMR features combined with molecular descriptors in Phase 2, and fuel-level surface tension predictions reached MAPE values as low as 1.9% for Shell-SPK and 3.0% for Gevo-ATJ using the NMR spectrum representation in Phase 3. Viscosity, by contrast, proved far more difficult. The best pure-compound viscosity model in Phase 1 achieved a mean hydrocarbon $R^2$ of only 0.70 across five folds even with molecular fingerprints that encode molecular weight, branching, and ring topology. NMR spectra alone performed substantially worse, with the Phase 2 NMR-only XGBoost model yielding negative $R^2$ values on multiple viscosity folds.

This disparity has a clear physical explanation. Surface tension is dominated by intermolecular interactions at the liquid--air interface and scales approximately linearly with temperature for hydrocarbons. The functional group inventory encoded in a $""^1"H"$ NMR spectrum, which directly quantifies aromatic, olefinic, and aliphatic content, captures the essential determinants of these interfacial forces @Parker2025DensityST. Viscosity, however, depends on the resistance to molecular rearrangement within the bulk liquid, which is exponentially sensitive to temperature through the Arrhenius relationship $ln eta = A + B slash T$. The pre-exponential factor $A$ and the activation energy parameter $B$ both depend strongly on molecular weight, chain length, and branching patterns that NMR chemical shifts encode only indirectly. A methylene peak at 1.3 ppm reports the presence of $"CH"_2$ groups but does not distinguish a $"C"_10$ chain from a $"C"_20$ chain. Because viscosity scales roughly as a power law with molecular weight @Poling2001, this ambiguity is catastrophic for viscosity prediction.

The Phase 2 combined models, which concatenated NMR spectral features with molecular descriptors including molecular weight, BCUT2D descriptors, and topological indices, achieved the best hydrocarbon viscosity $R^2$ of 0.694 with XGBoost. The Phase 1 model comparison further confirmed this pattern: the top-ranked features for viscosity prediction included QED, BCUT2D\_LOGPLOW, BCUT2D\_CHGHI, and HeavyAtomMolWt, all of which encode size and polarity information absent from the NMR spectrum itself. For surface tension, the combined XGBoost model achieved a hydrocarbon $R^2$ of 0.813, and even the NMR-only model reached 0.761, confirming that functional group distributions carry far more predictive power for interfacial properties than for bulk transport properties. The takeaway is not that NMR is uninformative for viscosity, but that it provides a necessary and incomplete description. Any practical NMR-based viscosity model must be augmented with explicit molecular weight or size descriptors, either measured independently (e.g., from gel permeation chromatography) or predicted from the spectrum itself.


== Transfer Learning: Promise and Distribution Shift <discussion-transfer>

The Phase 4 transfer learning experiments tested whether pretraining on a large corpus of NMR--descriptor pairs could compensate for the small number of compounds with both NMR spectra and measured viscosity. The pretraining dataset contained 296,000 compounds from the NMRexp database @Wang2025NMRexp, for which molecular descriptors were computed from SMILES structures. A multilayer perceptron trained on this corpus learned a general mapping from NMR features to molecular descriptors, which could then serve as a feature extractor for downstream viscosity prediction.

The direct application of the pretrained MLP to viscosity compounds failed, producing an average fuel MAPE of 44.9% in Phase 4 v2, worse than the 39.4% achieved by the simpler Phase 4 v1 XGBoost pipeline. The failure had a straightforward cause. The NMRexp database is dominated by drug-like molecules containing nitrogen, oxygen, sulfur, and halogen substituents, while the viscosity training set consists almost exclusively of hydrocarbons containing only carbon and hydrogen. The descriptor distributions learned during pretraining reflected this drug-like bias, and the model produced systematically incorrect descriptor estimates when applied to hydrocarbon inputs. This is a canonical example of distribution shift in transfer learning: the source domain (drug-like organic molecules) and target domain (hydrocarbon fuels) share the same input modality (NMR features) but occupy different regions of chemical space.

Fine-tuning the pretrained MLP on the 943 viscosity compounds in Phase 4 v3 reduced the average fuel MAPE from 39.4% to 29.3%, a 25.6% relative improvement over the non-pretrained baseline. This result demonstrates that transfer learning can extract useful representations from large NMR databases even when the domain mismatch is severe, provided that a fine-tuning step adapts the learned features to the target chemical space. The pretrained weights gave the model an informed initialization that captured general NMR--structure correlations, and fine-tuning on the small but domain-relevant viscosity dataset refined those weights to the hydrocarbon regime. Phase 4 v4, which added sample weighting to upweight hydrocarbons and cold-temperature data during fine-tuning, provided only marginal further improvement, suggesting that the remaining error is dominated by factors other than class imbalance in the fine-tuning set.

The improvement is meaningful but bounded by the fundamental scarcity of hydrocarbon--NMR--viscosity intersections in existing databases. The 943 compounds with both NMR spectra and viscosity measurements span a narrow range of hydrocarbon classes, predominantly normal alkanes, branched alkanes, and single-ring aromatics. Polycyclic naphthenes, multi-ring aromatics, and the heterogeneous mixture of structural types found in real jet fuels remain underrepresented. The transfer learning framework itself is sound, and its benefits would compound if the pretraining corpus were enriched with hydrocarbon-relevant compounds and the fine-tuning set were expanded with targeted experimental measurements.


== Why Computed Data Did Not Help <discussion-computed>

One of the more counterintuitive findings was that expanding the training set from experimental-only to computed viscosity data degraded performance rather than improving it. The computed viscosity pipeline used group contribution methods from the ChEDL library @Bell2025chemicals @Bell2025thermo to estimate viscosity for all 1.48 million NMRexp compounds with SMILES structures. This 1,500-fold expansion of the training set might have been expected to improve generalization by exposing the model to a far wider range of molecular structures.

In practice, the computed labels introduced systematic bias. Group contribution methods estimate viscosity by summing contributions from predefined structural fragments, an approach that works well for simple molecules within the calibration domain but produces biased estimates for molecules with unusual combinations of functional groups @Joback1987 @Constantinou1994. When these biased viscosity estimates were paired with NMR features that were themselves simulated rather than experimentally measured, the model was trained on doubly approximate data. The NMR features contained simulation artifacts from the GISSMO spin-system model @Dashti2017GISSMO, and the viscosity labels contained group contribution artifacts. The resulting model learned to map simulation noise to estimation noise rather than capturing the underlying structure--property relationship.

This finding has implications for the broader molecular machine learning community. The appeal of large computed datasets is obvious: they promise to overcome the data scarcity that limits supervised learning for many property prediction tasks. However, the quality of labels matters more than their quantity when the prediction target is a physical property with complex many-body origins. Viscosity arises from collective molecular dynamics that group contribution methods approximate crudely, and no amount of training data can overcome a systematic bias in the labels themselves. The path to better models runs through expanding the experimental intersection of NMR spectra and viscosity measurements, not through filling the gap with computed surrogates. This conclusion echoes findings in other domains of cheminformatics where computed training labels have been shown to introduce persistent biases that propagate through downstream models @Katritzky2010 @Chew2024.


== The Cold-Temperature Extrapolation Problem <discussion-cold>

The ASTM D1655 specification sets a maximum viscosity of 8.0 mm$""^2$/s at $-20 degree.c$ (253.15 K) for Jet A and at $-40 degree.c$ (233.15 K) for Jet A-1 @ASTMD1655. Predicting viscosity at these cold temperatures is therefore the most practically relevant capability for fuel screening, and it is precisely where the models perform worst. Phase 3 fuel predictions at 233.15 K showed dramatic underestimates across all three NMR representations. For Gevo-ATJ (POSF 10151), the measured viscosity at 233 K was 10.5 cSt while the NMR spectrum model predicted 0.87 cSt, an error exceeding 90%. For HRJ-Camelina (POSF 7720), the measured value was 11.4 cSt versus a prediction of 1.06 cSt. For Sasol-IPK (POSF 7629), the measurement was 6.4 cSt versus a prediction of 0.98 cSt. In every case the model catastrophically underestimated the viscosity at the specification-critical temperature while performing reasonably at 253 K, where predictions fell within 10--50% of measured values.

The root cause is data scarcity at low temperatures compounded by the nonlinear nature of the Arrhenius extrapolation. The training set analysis revealed that only 14 compounds had viscosity measurements below 240 K. The Arrhenius parameterization $ln eta = A + B slash T$ amplifies prediction errors at low temperatures because the $B slash T$ term grows as $T$ decreases. A 10% error in the estimated $B$ parameter produces a 10% error in $ln eta$ at 300 K but a 13% error at 233 K, and because viscosity is the exponential of $ln eta$, these errors compound multiplicatively in real units. In Phase 1, the neural network trained with the hybrid Arrhenius loss was observed to collapse the $B$ parameter toward zero for many compounds, effectively predicting temperature-independent viscosity. This collapse is a rational strategy for minimizing training loss when the model has never observed the steep viscosity upturn that occurs below 250 K for most hydrocarbons. With insufficient cold-temperature training examples to penalize the collapse, the optimizer finds a solution that sacrifices cold-temperature accuracy to minimize error over the bulk of the training data at ambient and elevated temperatures.

The cold-temperature problem is not unique to NMR-based models. Any data-driven approach trained predominantly on measurements between 280 and 370 K will fail to extrapolate the Arrhenius curve into the 220--250 K regime. The distinction between interpolation and extrapolation is fundamental and cannot be resolved by improving the molecular representation or the model architecture alone. Resolving this limitation requires either collecting substantially more cold-temperature viscosity data for NMR-characterized hydrocarbons, or incorporating physics-based constraints that enforce the correct asymptotic behavior of the Arrhenius relationship at low temperatures. The latter approach might take the form of constrained optimization that requires $B > 0$ and $d eta slash d T < 0$ everywhere, or a physics-informed loss function that penalizes violations of the Arrhenius monotonicity condition.


== Pure Compounds versus Fuel Mixtures <discussion-mixtures>

All models developed in Phases 1 through 4 were trained on pure-compound data and applied to fuel mixtures by treating the mixture NMR spectrum as if it arose from a single compound. This approximation is physically unjustified. A jet fuel typically contains hundreds of individual hydrocarbon species spanning a molecular weight range from roughly $"C"_8$ to $"C"_16$, with each species contributing to the bulk NMR spectrum in proportion to its mole fraction @Edwards2017 @Colket2017. The measured NMR spectrum of a fuel is the mole-fraction-weighted superposition of hundreds of individual spectra, each shifted and broadened according to the specific electronic environment of its constituent protons @Cookson1987 @FlowerSaxena2005.

When a model trained on pure compounds receives this superposition as input, it interprets the composite functional group distribution as belonging to a single hypothetical molecule. This fictitious molecule has fractional aromatic content, fractional branching, and an effective molecular weight that does not correspond to any real species in the mixture. For surface tension, which depends primarily on the functional group inventory and varies modestly with molecular weight, this single-compound approximation works surprisingly well. The Phase 3 results confirm this: surface tension predictions for five reference fuels achieved MAPE values between 1.9% (Shell-SPK) and 12.9% (Jet-A POSF 10325), with the best results for Fischer-Tropsch and hydroprocessed fuels that have relatively narrow compositional distributions. These SPK-type fuels are predominantly isoparaffinic, so their NMR spectra more closely resemble those of individual compounds than do the spectra of conventional petroleum-derived fuels.

For viscosity, the mixture approximation is far more damaging. Viscosity is a nonlinear function of composition that depends on intermolecular interactions between dissimilar species. The viscosity of a binary mixture of $n$-octane and $n$-hexadecane, for example, is not the mole-fraction average of the two pure-component viscosities. Well-established mixing rules exist @Poling2001, but they require knowing the identities and concentrations of the individual components, information that is lost when the model receives only the composite NMR spectrum. The consistently high MAPE values for fuel viscosity prediction, ranging from 31% for Shell-SPK in the functional groups representation to 152% for Shell-SPK in the NMR full representation, likely reflect this fundamental mismatch between pure-compound training and mixture-level inference at least as much as they reflect shortcomings in the NMR features themselves.

The discrepancy between SPK and conventional fuel accuracy further supports this interpretation. Shell-SPK, a Fischer-Tropsch fuel with a relatively uniform isoparaffinic composition, achieved a surface tension MAPE of 1.9%, while the compositionally diverse Jet-A POSF 10325 yielded a MAPE of 12.9%. Narrow compositional distributions make the single-compound approximation more defensible, and the model accuracy tracks this expectation consistently.


== Comparison to Prior Work <discussion-comparison>

The results of this work can be situated within the landscape of NMR-based fuel property prediction by comparison with two principal baselines. Burnett developed a pipeline using NMR spectra and functional group representations to predict physical properties of pure compounds, demonstrating that NMR features carry predictive information for density, boiling point, and refractive index @Burnett2024NMRProperty. The present work extends this approach to temperature-dependent viscosity and surface tension, finding that the same NMR features that succeed for single-temperature, single-value properties encounter severe difficulties when the Arrhenius temperature dependence of viscosity must be captured. The key difference is that boiling point and refractive index are scalar properties at fixed conditions, whereas viscosity is a function of temperature with an exponential sensitivity that places far greater demands on model accuracy.

Parker et al. pursued a distinct strategy using NMR atom types, in which the $""^1"H"$ spectrum is decomposed into structurally meaningful chemical shift regions and the integrated areas are used as descriptors @Parker2025DensityST. Their models achieved strong performance for density and surface tension of aviation fuels, consistent with the surface tension results obtained here using the functional group representation. The Parker atom-type framework has the advantage of chemical interpretability: each descriptor corresponds to a well-defined structural motif (aromatic CH, $alpha$-methylene, terminal methyl, etc.), and the model coefficients can be inspected directly to understand which structural features drive prediction. The binned spectrum and functional group representations used in the present work trade some of this interpretability for broader coverage of spectral features that may not map cleanly onto predefined atom types. The functional group representation in Phase 3 achieved surface tension MAPE values of 3.3% for Shell-SPK and Sasol-IPK, comparable to the accuracy reported by Parker et al. for similar fuel types, confirming that the atom-type decomposition and the broader functional group approach converge for surface tension when the spectral regions are defined appropriately.

The Phase 1 comparison between tree-based methods and neural networks adds nuance to the ongoing discussion about model architectures for tabular data @Grinsztajn2022. XGBoost achieved the best mean viscosity $R^2$ of 0.486 on the combined Arrhenius parameterization across five folds, outperforming Random Forest (0.474), Lasso (0.501), and Ridge (0.434), while the original neural network baseline achieved a reported $R^2$ of approximately 0.89 on standardized metrics. However, the neural network's advantage on standardized metrics did not translate to real-unit reconstruction. The mean hydrocarbon reconstruction $R^2$ across five folds for the neural network was 0.695, 0.762, 0.684, 0.743, and 0.633, averaging 0.703, while XGBoost achieved comparable values with substantially less training effort. The practical implication is that model architecture matters less than the quality and coverage of training data for this problem, particularly at the tails of the temperature distribution where all models fail.


== What Would Actually Improve Results <discussion-improvements>

The analysis across all four phases points to three specific investments in data collection and model development that would most substantially improve NMR-based fuel property prediction.

First, the single most impactful intervention would be collecting experimental viscosity measurements at temperatures between 220 and 260 K for a targeted set of hydrocarbons that already have NMR spectra in existing databases. The current training set contains only 14 compounds with data below 240 K, which is wholly insufficient to learn the steep viscosity upturn that governs specification compliance. A focused measurement campaign covering 50 to 100 representative hydrocarbons, spanning normal alkanes, isoparaffins, cycloparaffins, and mono- and polycyclic aromatics, would fill the gap that currently makes cold-temperature prediction impossible. The compounds should be selected to maximize coverage of the hydrocarbon structural space relevant to jet fuels while prioritizing species already present in the HMDB @Wishart2022HMDB, NMRexp @Wang2025NMRexp, or SDBS @SDBS2025 databases so that high-quality experimental NMR spectra are already available.

Second, collecting NMR spectra of fuel mixtures with simultaneously measured viscosity and surface tension would directly address the pure-compound-to-mixture transfer problem. Rather than training on pure compounds and hoping that the model generalizes to superposed spectra, a model trained on mixture NMR spectra paired with mixture property measurements would learn the correct composition--property relationship without requiring deconvolution of individual components. The NJFCP reference fuel set @Colket2017 @Edwards2017 provides a natural starting point, as these fuels have extensive property characterization and several already have published NMR spectra. Expanding this dataset to include SAF blends at various blend ratios would create a training corpus directly relevant to the fuel qualification task.

Third, developing mixture-aware model architectures that explicitly account for spectral superposition would address the conceptual mismatch between pure-compound training and mixture inference. One approach would decompose the mixture spectrum into component contributions using NMR deconvolution methods @Wei2022pSCNN @Ravanbakhsh2015BAYESIL, estimate pure-component properties for each identified species, and combine them using established mixing rules. An alternative would train end-to-end on mixture spectra, bypassing the deconvolution step entirely but requiring a sufficiently large training corpus of mixture NMR spectra paired with measured properties. Both approaches represent a substantial advance over the current single-compound approximation and would bring the modeling framework into alignment with the physical reality of multi-component fuel systems.


== Broader Implications for SAF Qualification <discussion-implications>

The ASTM D4054 evaluation process for new aviation turbine fuels requires extensive physical and chemical testing, typically spanning three to five years and costing millions of dollars per candidate feedstock @ASTMD4054 @Heyne2021. NMR-based property screening could accelerate the earliest stages of this process by providing rapid estimates of viscosity, surface tension, and density from a single five-minute NMR measurement requiring only microliters of sample. Even at the current accuracy levels, the surface tension model is sufficient for initial screening. With MAPE values below 7% for four of the five reference fuels tested in Phase 3, the model can identify candidate fuels whose surface tension falls outside specification limits well before expensive standardized testing begins. Surface tension is particularly amenable to early screening because the ASTM specification limits are relatively broad and the property varies smoothly with fuel composition.

For viscosity, the current best MAPE of 29.3% across reference fuels is insufficient for specification compliance decisions, where the margin between typical fuel viscosities (3--5 cSt at $-20 degree.c$) and the 8.0 mm$""^2$/s limit is often less than a factor of two. Achieving a MAPE below 10% for cold-temperature viscosity would make NMR-based screening practically useful for go/no-go decisions on candidate SAF blends. The path to this accuracy, as outlined in @discussion-improvements, requires targeted cold-temperature experimental measurements, mixture-level training data, and models that respect the Arrhenius physics of viscosity--temperature dependence. None of these requirements is technically insurmountable, but each demands a focused investment of experimental and computational resources that goes beyond what existing public databases provide.

The value of NMR as a screening measurement extends beyond prediction accuracy. An NMR spectrum is acquired non-destructively, requires minimal sample preparation, and produces a permanent digital record that can be compared against reference databases, reanalyzed as models improve, and shared across laboratories in standardized formats @Hoch2023BMRB @Patil2023nmrXiv. These operational advantages mean that NMR-based screening could be integrated into the earliest stages of SAF development, where hundreds of candidate blends may need to be evaluated rapidly and only a handful will proceed to full ASTM D4054 testing. If the prediction accuracy can be improved to the 5--10% MAPE range through the targeted data collection and modeling investments described above, NMR spectroscopy could transition from a structural characterization tool to a quantitative property prediction platform, substantially reducing the time and cost of qualifying new sustainable aviation fuels for commercial flight.
