// 07-conclusion.typ — Conclusion

This report presented a four-phase machine-learning pipeline for predicting thermophysical properties of organic compounds and aviation fuel mixtures directly from nuclear magnetic resonance spectra. The pipeline was developed incrementally, with each phase addressing a specific limitation revealed by the preceding one, and its progression illustrates both the promise and the present constraints of NMR-based property prediction.

Phase~1 established baseline models using molecular fingerprints (Morgan, MACCS, and RDKit) as the sole input representation. XGBoost regression on these fingerprints achieved $R^2 = 0.638$ for viscosity prediction on pure compounds, confirming that structural descriptors derived from SMILES strings carry substantial information about bulk transport properties but leave a meaningful fraction of the variance unexplained. Phase~2 introduced NMR spectral features, both binned $""^1"H"$ and $""^(13)"C"$ spectra and summary statistics extracted from them. NMR features alone proved insufficient for accurate viscosity prediction, a finding attributable to the ambiguity that arises when many structurally distinct molecules share similar spectral envelopes. However, concatenating NMR descriptors with molecular fingerprints raised the best pure-compound viscosity model to $R^2 = 0.694$ and the surface-tension model to $R^2 = 0.813$, demonstrating that NMR features capture complementary physicochemical information that fingerprints miss.

Phase~3 extended prediction from pure compounds to real aviation fuel mixtures by constructing composition-weighted spectral descriptors from functional-group analyses. Applied to viscosity prediction across five POSF reference fuels spanning $-20$ to $80 °C$, the Phase~3 model achieved 53.8\% mean absolute percentage error. Although this error is too large for final fuel qualification, it represents a meaningful first demonstration of NMR-to-mixture-property prediction in a regime where training data are extremely scarce. Phase~4 attacked the data scarcity problem through transfer learning. A multilayer perceptron was first pretrained on 296,000 pure-compound NMR--viscosity pairs to learn general spectral-to-viscosity mappings and then fine-tuned on only 943 fuel-relevant compounds. This strategy reduced mixture viscosity MAPE to 29.3\%, a 46\% relative improvement over the Phase~3 baseline, confirming that representations learned from abundant pure-compound data transfer usefully to the mixture domain.

A critical enabler of the transfer-learning approach was the assembly of the largest known NMR feature dataset, encompassing 1.8 million compounds drawn from 14 public and proprietary spectral databases. Despite this scale, the binding constraint on model performance remains the narrow intersection between NMR coverage and experimental thermophysical measurements. Only 953 compounds currently reside at the NMR--viscosity intersection with reliable experimental data, and this bottleneck limits both the diversity of chemical space the models can learn from and the statistical power of downstream evaluations.

Several directions for future work follow naturally from these findings. First, expanding the experimental viscosity and surface-tension corpus, particularly for oxygenated and cyclic compounds prevalent in SAF candidate streams, would directly widen the training distribution and reduce extrapolation error. Second, developing mixture-aware architectures that explicitly model intermolecular interactions, rather than relying on composition-weighted averaging of pure-component descriptors, could capture nonideal mixing effects that the current pipeline neglects. Third, extending temperature coverage below $-40 °C$ is essential for predicting cold-flow behavior under the most demanding flight conditions. Taken together, these advances would move NMR-based property prediction from a screening tool toward a quantitative surrogate for laboratory measurement, accelerating the evaluation and qualification of sustainable aviation fuels at a pace commensurate with the industry's decarbonization goals.
